/*
 * DOJAH Publilc APIs
 * Use Dojah to verify, onboard and manage user identity across Africa!
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.dojah.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.dojah.client.model.FraudScreenUserResponseEntityIpCheckResultAnonymity;
import com.konfigthis.dojah.client.model.FraudScreenUserResponseEntityIpCheckResultBlacklists;
import com.konfigthis.dojah.client.model.FraudScreenUserResponseEntityIpCheckResultIpDetails;
import com.konfigthis.dojah.client.model.FraudScreenUserResponseEntityIpCheckResultRiskScore;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for FraudScreenUserResponseEntityIpCheckResult
 */
public class FraudScreenUserResponseEntityIpCheckResultTest {
    private final FraudScreenUserResponseEntityIpCheckResult model = new FraudScreenUserResponseEntityIpCheckResult();

    /**
     * Model tests for FraudScreenUserResponseEntityIpCheckResult
     */
    @Test
    public void testFraudScreenUserResponseEntityIpCheckResult() {
        // TODO: test FraudScreenUserResponseEntityIpCheckResult
    }

    /**
     * Test the property 'ip'
     */
    @Test
    public void ipTest() {
        // TODO: test ip
    }

    /**
     * Test the property 'blacklists'
     */
    @Test
    public void blacklistsTest() {
        // TODO: test blacklists
    }

    /**
     * Test the property 'anonymity'
     */
    @Test
    public void anonymityTest() {
        // TODO: test anonymity
    }

    /**
     * Test the property 'riskScore'
     */
    @Test
    public void riskScoreTest() {
        // TODO: test riskScore
    }

    /**
     * Test the property 'ipDetails'
     */
    @Test
    public void ipDetailsTest() {
        // TODO: test ipDetails
    }

}
