/*
 * DOJAH APIs
 * Use Dojah to verify, onboard and manage user identity across Africa!
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.dojah.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for GetAccountAnalysisResponseEntityFundsManagement
 */
public class GetAccountAnalysisResponseEntityFundsManagementTest {
    private final GetAccountAnalysisResponseEntityFundsManagement model = new GetAccountAnalysisResponseEntityFundsManagement();

    /**
     * Model tests for GetAccountAnalysisResponseEntityFundsManagement
     */
    @Test
    public void testGetAccountAnalysisResponseEntityFundsManagement() {
        // TODO: test GetAccountAnalysisResponseEntityFundsManagement
    }

    /**
     * Test the property 'accountActivity'
     */
    @Test
    public void accountActivityTest() {
        // TODO: test accountActivity
    }

    /**
     * Test the property 'accountSweep'
     */
    @Test
    public void accountSweepTest() {
        // TODO: test accountSweep
    }

    /**
     * Test the property 'averageMonthlyLoanAmount'
     */
    @Test
    public void averageMonthlyLoanAmountTest() {
        // TODO: test averageMonthlyLoanAmount
    }

    /**
     * Test the property 'averageMonthlyLoanRepaymentAmount'
     */
    @Test
    public void averageMonthlyLoanRepaymentAmountTest() {
        // TODO: test averageMonthlyLoanRepaymentAmount
    }

    /**
     * Test the property 'gamblingRate'
     */
    @Test
    public void gamblingRateTest() {
        // TODO: test gamblingRate
    }

    /**
     * Test the property 'gamblingStatus'
     */
    @Test
    public void gamblingStatusTest() {
        // TODO: test gamblingStatus
    }

    /**
     * Test the property 'loanInflowAmount'
     */
    @Test
    public void loanInflowAmountTest() {
        // TODO: test loanInflowAmount
    }

    /**
     * Test the property 'loanRepaymentToInflowAmount'
     */
    @Test
    public void loanRepaymentToInflowAmountTest() {
        // TODO: test loanRepaymentToInflowAmount
    }

    /**
     * Test the property 'monthToMonthInflowToOutflowAmount'
     */
    @Test
    public void monthToMonthInflowToOutflowAmountTest() {
        // TODO: test monthToMonthInflowToOutflowAmount
    }

    /**
     * Test the property 'numberOfCreditLoanTransactions'
     */
    @Test
    public void numberOfCreditLoanTransactionsTest() {
        // TODO: test numberOfCreditLoanTransactions
    }

    /**
     * Test the property 'numberOfDebitRepaymentTransactions'
     */
    @Test
    public void numberOfDebitRepaymentTransactionsTest() {
        // TODO: test numberOfDebitRepaymentTransactions
    }

    /**
     * Test the property 'overallInflowToOutflowAmount'
     */
    @Test
    public void overallInflowToOutflowAmountTest() {
        // TODO: test overallInflowToOutflowAmount
    }

    /**
     * Test the property 'percentOfInflowIrregularity'
     */
    @Test
    public void percentOfInflowIrregularityTest() {
        // TODO: test percentOfInflowIrregularity
    }

    /**
     * Test the property 'totalLoanAmount'
     */
    @Test
    public void totalLoanAmountTest() {
        // TODO: test totalLoanAmount
    }

    /**
     * Test the property 'totalLoanRepaymentAmount'
     */
    @Test
    public void totalLoanRepaymentAmountTest() {
        // TODO: test totalLoanRepaymentAmount
    }

}
