/*
 * DOJAH APIs
 * Use Dojah to verify, onboard and manage user identity across Africa!
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.dojah.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.dojah.client.model.GetEmailReputationResponseEntityDetails;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for GetEmailReputationResponseEntity
 */
public class GetEmailReputationResponseEntityTest {
    private final GetEmailReputationResponseEntity model = new GetEmailReputationResponseEntity();

    /**
     * Model tests for GetEmailReputationResponseEntity
     */
    @Test
    public void testGetEmailReputationResponseEntity() {
        // TODO: test GetEmailReputationResponseEntity
    }

    /**
     * Test the property 'email'
     */
    @Test
    public void emailTest() {
        // TODO: test email
    }

    /**
     * Test the property 'reputation'
     */
    @Test
    public void reputationTest() {
        // TODO: test reputation
    }

    /**
     * Test the property 'suspicious'
     */
    @Test
    public void suspiciousTest() {
        // TODO: test suspicious
    }

    /**
     * Test the property 'references'
     */
    @Test
    public void referencesTest() {
        // TODO: test references
    }

    /**
     * Test the property 'details'
     */
    @Test
    public void detailsTest() {
        // TODO: test details
    }

}
