/*
 * DOJAH APIs
 * Use Dojah to verify, onboard and manage user identity across Africa!
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.dojah.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for GetSpendingPatternResponseEntityPatternOthers
 */
public class GetSpendingPatternResponseEntityPatternOthersTest {
    private final GetSpendingPatternResponseEntityPatternOthers model = new GetSpendingPatternResponseEntityPatternOthers();

    /**
     * Model tests for GetSpendingPatternResponseEntityPatternOthers
     */
    @Test
    public void testGetSpendingPatternResponseEntityPatternOthers() {
        // TODO: test GetSpendingPatternResponseEntityPatternOthers
    }

    /**
     * Test the property 'sum'
     */
    @Test
    public void sumTest() {
        // TODO: test sum
    }

    /**
     * Test the property 'count'
     */
    @Test
    public void countTest() {
        // TODO: test count
    }

    /**
     * Test the property 'percentage'
     */
    @Test
    public void percentageTest() {
        // TODO: test percentage
    }

}
