/*
 * DOJAH Publilc APIs
 * Use Dojah to verify, onboard and manage user identity across Africa!
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.dojah.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for GetVinResponseEntity
 */
public class GetVinResponseEntityTest {
    private final GetVinResponseEntity model = new GetVinResponseEntity();

    /**
     * Model tests for GetVinResponseEntity
     */
    @Test
    public void testGetVinResponseEntity() {
        // TODO: test GetVinResponseEntity
    }

    /**
     * Test the property 'fullName'
     */
    @Test
    public void fullNameTest() {
        // TODO: test fullName
    }

    /**
     * Test the property 'voterIdentificationNumberColon'
     */
    @Test
    public void voterIdentificationNumberColonTest() {
        // TODO: test voterIdentificationNumberColon
    }

    /**
     * Test the property 'genderColon'
     */
    @Test
    public void genderColonTest() {
        // TODO: test genderColon
    }

    /**
     * Test the property 'occupationColon'
     */
    @Test
    public void occupationColonTest() {
        // TODO: test occupationColon
    }

    /**
     * Test the property 'timeOfRegistrationColon'
     */
    @Test
    public void timeOfRegistrationColonTest() {
        // TODO: test timeOfRegistrationColon
    }

    /**
     * Test the property 'stateColon'
     */
    @Test
    public void stateColonTest() {
        // TODO: test stateColon
    }

    /**
     * Test the property 'localGovernmentColon'
     */
    @Test
    public void localGovernmentColonTest() {
        // TODO: test localGovernmentColon
    }

    /**
     * Test the property 'registrationAreaWardColon'
     */
    @Test
    public void registrationAreaWardColonTest() {
        // TODO: test registrationAreaWardColon
    }

    /**
     * Test the property 'pollingUnitColon'
     */
    @Test
    public void pollingUnitColonTest() {
        // TODO: test pollingUnitColon
    }

    /**
     * Test the property 'pollingUnitCode'
     */
    @Test
    public void pollingUnitCodeTest() {
        // TODO: test pollingUnitCode
    }

}
