# coding: utf-8

"""
    DOJAH APIs

    Use Dojah to verify, onboard and manage user identity across Africa!

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

import unittest

import dojah_client
from dojah_client.model.get_basic_phone_number_response import GetBasicPhoneNumberResponse
from dojah_client import configuration


class TestGetBasicPhoneNumberResponse(unittest.TestCase):
    """GetBasicPhoneNumberResponse unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
