/*
 * DOJAH Publilc APIs
 * Use Dojah to verify, onboard and manage user identity across Africa!
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.dojah.client.api;

import com.konfigthis.dojah.client.ApiException;
import com.konfigthis.dojah.client.ApiClient;
import com.konfigthis.dojah.client.ApiException;
import com.konfigthis.dojah.client.Configuration;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for GlobalKycApi
 */
@Disabled
public class GlobalKycApiTest {

    private static GlobalKycApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new GlobalKycApi(apiClient);
    }

    /**
     * Canada Ekyc
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void caEkycTest() throws ApiException {
        String country = null;
        String firstName = null;
        String lastName = null;
        String streetName = null;
        String dateOfBirth = null;
        Integer houseNumber = null;
        Integer postCode = null;
        Object response = api.caEkyc()
                .country(country)
                .firstName(firstName)
                .lastName(lastName)
                .streetName(streetName)
                .dateOfBirth(dateOfBirth)
                .houseNumber(houseNumber)
                .postCode(postCode)
                .execute();
        // TODO: test validations
    }

    /**
     * US SSN
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getUsSsnTest() throws ApiException {
        String country = null;
        String firstName = null;
        String lastName = null;
        String streetName = null;
        String dateOfBirth = null;
        Integer houseNumber = null;
        Integer postCode = null;
        Object response = api.getUsSsn()
                .country(country)
                .firstName(firstName)
                .lastName(lastName)
                .streetName(streetName)
                .dateOfBirth(dateOfBirth)
                .houseNumber(houseNumber)
                .postCode(postCode)
                .execute();
        // TODO: test validations
    }

    /**
     * UK 2+2
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void ukTwoPlusTwoTest() throws ApiException {
        String country = null;
        String firstName = null;
        String lastName = null;
        String streetName = null;
        String dateOfBirth = null;
        Integer houseNumber = null;
        Integer postCode = null;
        Object response = api.ukTwoPlusTwo()
                .country(country)
                .firstName(firstName)
                .lastName(lastName)
                .streetName(streetName)
                .dateOfBirth(dateOfBirth)
                .houseNumber(houseNumber)
                .postCode(postCode)
                .execute();
        // TODO: test validations
    }

}
