/*
 * DOJAH Publilc APIs
 *
 * Use Dojah to verify, onboard and manage user identity across Africa!
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://konfigthis.com
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Dojah.Net.Api;
using Dojah.Net.Model;
using Dojah.Net.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Dojah.Net.Test.Model
{
    /// <summary>
    ///  Class for testing AmlScreenAmlResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Konfig (https://konfigthis.com).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AmlScreenAmlResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AmlScreenAmlResponse
        //private AmlScreenAmlResponse instance;

        public AmlScreenAmlResponseTests()
        {
            // TODO uncomment below to create an instance of AmlScreenAmlResponse
            //instance = new AmlScreenAmlResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AmlScreenAmlResponse
        /// </summary>
        [Fact]
        public void AmlScreenAmlResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" AmlScreenAmlResponse
            //Assert.IsType<AmlScreenAmlResponse>(instance);
        }


        /// <summary>
        /// Test the property 'Entity'
        /// </summary>
        [Fact]
        public void EntityTest()
        {
            // TODO unit test for the property 'Entity'
        }

    }

}
