/*
 * DOJAH APIs
 *
 * Use Dojah to verify, onboard and manage user identity across Africa!
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://konfigthis.com
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Dojah.Net.Api;
using Dojah.Net.Model;
using Dojah.Net.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Dojah.Net.Test.Model
{
    /// <summary>
    ///  Class for testing CollectStatusFromPdfRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Konfig (https://konfigthis.com).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CollectStatusFromPdfRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CollectStatusFromPdfRequest
        //private CollectStatusFromPdfRequest instance;

        public CollectStatusFromPdfRequestTests()
        {
            // TODO uncomment below to create an instance of CollectStatusFromPdfRequest
            //instance = new CollectStatusFromPdfRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CollectStatusFromPdfRequest
        /// </summary>
        [Fact]
        public void CollectStatusFromPdfRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" CollectStatusFromPdfRequest
            //Assert.IsType<CollectStatusFromPdfRequest>(instance);
        }


        /// <summary>
        /// Test the property 'Statement'
        /// </summary>
        [Fact]
        public void StatementTest()
        {
            // TODO unit test for the property 'Statement'
        }
        /// <summary>
        /// Test the property 'BankCode'
        /// </summary>
        [Fact]
        public void BankCodeTest()
        {
            // TODO unit test for the property 'BankCode'
        }

    }

}
