/*
 * DOJAH Publilc APIs
 *
 * Use Dojah to verify, onboard and manage user identity across Africa!
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://konfigthis.com
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Dojah.Net.Api;
using Dojah.Net.Model;
using Dojah.Net.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Dojah.Net.Test.Model
{
    /// <summary>
    ///  Class for testing FraudScreenPhoneResponseEntity
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Konfig (https://konfigthis.com).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class FraudScreenPhoneResponseEntityTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for FraudScreenPhoneResponseEntity
        //private FraudScreenPhoneResponseEntity instance;

        public FraudScreenPhoneResponseEntityTests()
        {
            // TODO uncomment below to create an instance of FraudScreenPhoneResponseEntity
            //instance = new FraudScreenPhoneResponseEntity();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of FraudScreenPhoneResponseEntity
        /// </summary>
        [Fact]
        public void FraudScreenPhoneResponseEntityInstanceTest()
        {
            // TODO uncomment below to test "IsType" FraudScreenPhoneResponseEntity
            //Assert.IsType<FraudScreenPhoneResponseEntity>(instance);
        }


        /// <summary>
        /// Test the property 'Number'
        /// </summary>
        [Fact]
        public void NumberTest()
        {
            // TODO unit test for the property 'Number'
        }
        /// <summary>
        /// Test the property 'Valid'
        /// </summary>
        [Fact]
        public void ValidTest()
        {
            // TODO unit test for the property 'Valid'
        }
        /// <summary>
        /// Test the property 'Disposable'
        /// </summary>
        [Fact]
        public void DisposableTest()
        {
            // TODO unit test for the property 'Disposable'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'Country'
        /// </summary>
        [Fact]
        public void CountryTest()
        {
            // TODO unit test for the property 'Country'
        }
        /// <summary>
        /// Test the property 'Carrier'
        /// </summary>
        [Fact]
        public void CarrierTest()
        {
            // TODO unit test for the property 'Carrier'
        }
        /// <summary>
        /// Test the property 'Score'
        /// </summary>
        [Fact]
        public void ScoreTest()
        {
            // TODO unit test for the property 'Score'
        }
        /// <summary>
        /// Test the property 'AccountDetailsRegistered'
        /// </summary>
        [Fact]
        public void AccountDetailsRegisteredTest()
        {
            // TODO unit test for the property 'AccountDetailsRegistered'
        }

    }

}
