/*
 * DOJAH APIs
 *
 * Use Dojah to verify, onboard and manage user identity across Africa!
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://konfigthis.com
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Dojah.Net.Api;
using Dojah.Net.Model;
using Dojah.Net.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Dojah.Net.Test.Model
{
    /// <summary>
    ///  Class for testing GetOcrTextResponseEntity
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Konfig (https://konfigthis.com).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetOcrTextResponseEntityTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetOcrTextResponseEntity
        //private GetOcrTextResponseEntity instance;

        public GetOcrTextResponseEntityTests()
        {
            // TODO uncomment below to create an instance of GetOcrTextResponseEntity
            //instance = new GetOcrTextResponseEntity();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetOcrTextResponseEntity
        /// </summary>
        [Fact]
        public void GetOcrTextResponseEntityInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetOcrTextResponseEntity
            //Assert.IsType<GetOcrTextResponseEntity>(instance);
        }


        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Fact]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }

    }

}
