/*
 * DOJAH APIs
 *
 * Use Dojah to verify, onboard and manage user identity across Africa!
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://konfigthis.com
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Dojah.Net.Api;
using Dojah.Net.Model;
using Dojah.Net.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Dojah.Net.Test.Model
{
    /// <summary>
    ///  Class for testing VerifySelfieNinResponseEntity
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Konfig (https://konfigthis.com).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class VerifySelfieNinResponseEntityTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for VerifySelfieNinResponseEntity
        //private VerifySelfieNinResponseEntity instance;

        public VerifySelfieNinResponseEntityTests()
        {
            // TODO uncomment below to create an instance of VerifySelfieNinResponseEntity
            //instance = new VerifySelfieNinResponseEntity();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of VerifySelfieNinResponseEntity
        /// </summary>
        [Fact]
        public void VerifySelfieNinResponseEntityInstanceTest()
        {
            // TODO uncomment below to test "IsType" VerifySelfieNinResponseEntity
            //Assert.IsType<VerifySelfieNinResponseEntity>(instance);
        }


        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Fact]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }
        /// <summary>
        /// Test the property 'Nin'
        /// </summary>
        [Fact]
        public void NinTest()
        {
            // TODO unit test for the property 'Nin'
        }
        /// <summary>
        /// Test the property 'Firstname'
        /// </summary>
        [Fact]
        public void FirstnameTest()
        {
            // TODO unit test for the property 'Firstname'
        }
        /// <summary>
        /// Test the property 'Middlename'
        /// </summary>
        [Fact]
        public void MiddlenameTest()
        {
            // TODO unit test for the property 'Middlename'
        }
        /// <summary>
        /// Test the property 'Surname'
        /// </summary>
        [Fact]
        public void SurnameTest()
        {
            // TODO unit test for the property 'Surname'
        }
        /// <summary>
        /// Test the property 'Maidenname'
        /// </summary>
        [Fact]
        public void MaidennameTest()
        {
            // TODO unit test for the property 'Maidenname'
        }
        /// <summary>
        /// Test the property 'Telephoneno'
        /// </summary>
        [Fact]
        public void TelephonenoTest()
        {
            // TODO unit test for the property 'Telephoneno'
        }
        /// <summary>
        /// Test the property 'State'
        /// </summary>
        [Fact]
        public void StateTest()
        {
            // TODO unit test for the property 'State'
        }
        /// <summary>
        /// Test the property 'Place'
        /// </summary>
        [Fact]
        public void PlaceTest()
        {
            // TODO unit test for the property 'Place'
        }
        /// <summary>
        /// Test the property 'Profession'
        /// </summary>
        [Fact]
        public void ProfessionTest()
        {
            // TODO unit test for the property 'Profession'
        }
        /// <summary>
        /// Test the property 'Height'
        /// </summary>
        [Fact]
        public void HeightTest()
        {
            // TODO unit test for the property 'Height'
        }
        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Fact]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }
        /// <summary>
        /// Test the property 'Birthdate'
        /// </summary>
        [Fact]
        public void BirthdateTest()
        {
            // TODO unit test for the property 'Birthdate'
        }
        /// <summary>
        /// Test the property 'Birthstate'
        /// </summary>
        [Fact]
        public void BirthstateTest()
        {
            // TODO unit test for the property 'Birthstate'
        }
        /// <summary>
        /// Test the property 'Birthcountry'
        /// </summary>
        [Fact]
        public void BirthcountryTest()
        {
            // TODO unit test for the property 'Birthcountry'
        }
        /// <summary>
        /// Test the property 'CentralID'
        /// </summary>
        [Fact]
        public void CentralIDTest()
        {
            // TODO unit test for the property 'CentralID'
        }
        /// <summary>
        /// Test the property 'Documentno'
        /// </summary>
        [Fact]
        public void DocumentnoTest()
        {
            // TODO unit test for the property 'Documentno'
        }
        /// <summary>
        /// Test the property 'Educationallevel'
        /// </summary>
        [Fact]
        public void EducationallevelTest()
        {
            // TODO unit test for the property 'Educationallevel'
        }
        /// <summary>
        /// Test the property 'Employmentstatus'
        /// </summary>
        [Fact]
        public void EmploymentstatusTest()
        {
            // TODO unit test for the property 'Employmentstatus'
        }
        /// <summary>
        /// Test the property 'NokFirstname'
        /// </summary>
        [Fact]
        public void NokFirstnameTest()
        {
            // TODO unit test for the property 'NokFirstname'
        }
        /// <summary>
        /// Test the property 'NokLastname'
        /// </summary>
        [Fact]
        public void NokLastnameTest()
        {
            // TODO unit test for the property 'NokLastname'
        }
        /// <summary>
        /// Test the property 'NokMiddlename'
        /// </summary>
        [Fact]
        public void NokMiddlenameTest()
        {
            // TODO unit test for the property 'NokMiddlename'
        }
        /// <summary>
        /// Test the property 'NokAddress1'
        /// </summary>
        [Fact]
        public void NokAddress1Test()
        {
            // TODO unit test for the property 'NokAddress1'
        }
        /// <summary>
        /// Test the property 'NokAddress2'
        /// </summary>
        [Fact]
        public void NokAddress2Test()
        {
            // TODO unit test for the property 'NokAddress2'
        }
        /// <summary>
        /// Test the property 'NokLga'
        /// </summary>
        [Fact]
        public void NokLgaTest()
        {
            // TODO unit test for the property 'NokLga'
        }
        /// <summary>
        /// Test the property 'NokState'
        /// </summary>
        [Fact]
        public void NokStateTest()
        {
            // TODO unit test for the property 'NokState'
        }
        /// <summary>
        /// Test the property 'NokTown'
        /// </summary>
        [Fact]
        public void NokTownTest()
        {
            // TODO unit test for the property 'NokTown'
        }
        /// <summary>
        /// Test the property 'NokPostalcode'
        /// </summary>
        [Fact]
        public void NokPostalcodeTest()
        {
            // TODO unit test for the property 'NokPostalcode'
        }
        /// <summary>
        /// Test the property 'Othername'
        /// </summary>
        [Fact]
        public void OthernameTest()
        {
            // TODO unit test for the property 'Othername'
        }
        /// <summary>
        /// Test the property 'Pfirstname'
        /// </summary>
        [Fact]
        public void PfirstnameTest()
        {
            // TODO unit test for the property 'Pfirstname'
        }
        /// <summary>
        /// Test the property 'Photo'
        /// </summary>
        [Fact]
        public void PhotoTest()
        {
            // TODO unit test for the property 'Photo'
        }
        /// <summary>
        /// Test the property 'Pmiddlename'
        /// </summary>
        [Fact]
        public void PmiddlenameTest()
        {
            // TODO unit test for the property 'Pmiddlename'
        }
        /// <summary>
        /// Test the property 'Psurname'
        /// </summary>
        [Fact]
        public void PsurnameTest()
        {
            // TODO unit test for the property 'Psurname'
        }
        /// <summary>
        /// Test the property 'Nspokenlang'
        /// </summary>
        [Fact]
        public void NspokenlangTest()
        {
            // TODO unit test for the property 'Nspokenlang'
        }
        /// <summary>
        /// Test the property 'Ospokenlang'
        /// </summary>
        [Fact]
        public void OspokenlangTest()
        {
            // TODO unit test for the property 'Ospokenlang'
        }
        /// <summary>
        /// Test the property 'Religion'
        /// </summary>
        [Fact]
        public void ReligionTest()
        {
            // TODO unit test for the property 'Religion'
        }
        /// <summary>
        /// Test the property 'ResidenceTown'
        /// </summary>
        [Fact]
        public void ResidenceTownTest()
        {
            // TODO unit test for the property 'ResidenceTown'
        }
        /// <summary>
        /// Test the property 'ResidenceLga'
        /// </summary>
        [Fact]
        public void ResidenceLgaTest()
        {
            // TODO unit test for the property 'ResidenceLga'
        }
        /// <summary>
        /// Test the property 'ResidenceState'
        /// </summary>
        [Fact]
        public void ResidenceStateTest()
        {
            // TODO unit test for the property 'ResidenceState'
        }
        /// <summary>
        /// Test the property 'Residencestatus'
        /// </summary>
        [Fact]
        public void ResidencestatusTest()
        {
            // TODO unit test for the property 'Residencestatus'
        }
        /// <summary>
        /// Test the property 'ResidenceAddressLine1'
        /// </summary>
        [Fact]
        public void ResidenceAddressLine1Test()
        {
            // TODO unit test for the property 'ResidenceAddressLine1'
        }
        /// <summary>
        /// Test the property 'ResidenceAddressLine2'
        /// </summary>
        [Fact]
        public void ResidenceAddressLine2Test()
        {
            // TODO unit test for the property 'ResidenceAddressLine2'
        }
        /// <summary>
        /// Test the property 'SelfOriginLga'
        /// </summary>
        [Fact]
        public void SelfOriginLgaTest()
        {
            // TODO unit test for the property 'SelfOriginLga'
        }
        /// <summary>
        /// Test the property 'SelfOriginPlace'
        /// </summary>
        [Fact]
        public void SelfOriginPlaceTest()
        {
            // TODO unit test for the property 'SelfOriginPlace'
        }
        /// <summary>
        /// Test the property 'SelfOriginState'
        /// </summary>
        [Fact]
        public void SelfOriginStateTest()
        {
            // TODO unit test for the property 'SelfOriginState'
        }
        /// <summary>
        /// Test the property 'Signature'
        /// </summary>
        [Fact]
        public void SignatureTest()
        {
            // TODO unit test for the property 'Signature'
        }
        /// <summary>
        /// Test the property 'Nationality'
        /// </summary>
        [Fact]
        public void NationalityTest()
        {
            // TODO unit test for the property 'Nationality'
        }
        /// <summary>
        /// Test the property 'Gender'
        /// </summary>
        [Fact]
        public void GenderTest()
        {
            // TODO unit test for the property 'Gender'
        }
        /// <summary>
        /// Test the property 'TrackingId'
        /// </summary>
        [Fact]
        public void TrackingIdTest()
        {
            // TODO unit test for the property 'TrackingId'
        }
        /// <summary>
        /// Test the property 'SelfieVerification'
        /// </summary>
        [Fact]
        public void SelfieVerificationTest()
        {
            // TODO unit test for the property 'SelfieVerification'
        }

    }

}
