/*
 * DOJAH Publilc APIs
 *
 * Use Dojah to verify, onboard and manage user identity across Africa!
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://konfigthis.com
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Dojah.Net.Api;
using Dojah.Net.Model;
using Dojah.Net.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Dojah.Net.Test.Model
{
    /// <summary>
    ///  Class for testing ZafKycGetIdResponseEntity
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Konfig (https://konfigthis.com).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ZafKycGetIdResponseEntityTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ZafKycGetIdResponseEntity
        //private ZafKycGetIdResponseEntity instance;

        public ZafKycGetIdResponseEntityTests()
        {
            // TODO uncomment below to create an instance of ZafKycGetIdResponseEntity
            //instance = new ZafKycGetIdResponseEntity();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ZafKycGetIdResponseEntity
        /// </summary>
        [Fact]
        public void ZafKycGetIdResponseEntityInstanceTest()
        {
            // TODO uncomment below to test "IsType" ZafKycGetIdResponseEntity
            //Assert.IsType<ZafKycGetIdResponseEntity>(instance);
        }


        /// <summary>
        /// Test the property 'BirthPlaceCountry'
        /// </summary>
        [Fact]
        public void BirthPlaceCountryTest()
        {
            // TODO unit test for the property 'BirthPlaceCountry'
        }
        /// <summary>
        /// Test the property 'BirthPlaceCountryCode'
        /// </summary>
        [Fact]
        public void BirthPlaceCountryCodeTest()
        {
            // TODO unit test for the property 'BirthPlaceCountryCode'
        }
        /// <summary>
        /// Test the property 'BookedDate'
        /// </summary>
        [Fact]
        public void BookedDateTest()
        {
            // TODO unit test for the property 'BookedDate'
        }
        /// <summary>
        /// Test the property 'CardDate'
        /// </summary>
        [Fact]
        public void CardDateTest()
        {
            // TODO unit test for the property 'CardDate'
        }
        /// <summary>
        /// Test the property 'DateOfBirth'
        /// </summary>
        [Fact]
        public void DateOfBirthTest()
        {
            // TODO unit test for the property 'DateOfBirth'
        }
        /// <summary>
        /// Test the property 'FullName'
        /// </summary>
        [Fact]
        public void FullNameTest()
        {
            // TODO unit test for the property 'FullName'
        }
        /// <summary>
        /// Test the property 'Gender'
        /// </summary>
        [Fact]
        public void GenderTest()
        {
            // TODO unit test for the property 'Gender'
        }
        /// <summary>
        /// Test the property 'IdBlocked'
        /// </summary>
        [Fact]
        public void IdBlockedTest()
        {
            // TODO unit test for the property 'IdBlocked'
        }
        /// <summary>
        /// Test the property 'IdNumber'
        /// </summary>
        [Fact]
        public void IdNumberTest()
        {
            // TODO unit test for the property 'IdNumber'
        }
        /// <summary>
        /// Test the property 'IssuedDate'
        /// </summary>
        [Fact]
        public void IssuedDateTest()
        {
            // TODO unit test for the property 'IssuedDate'
        }
        /// <summary>
        /// Test the property 'LastName'
        /// </summary>
        [Fact]
        public void LastNameTest()
        {
            // TODO unit test for the property 'LastName'
        }
        /// <summary>
        /// Test the property 'MaidenName'
        /// </summary>
        [Fact]
        public void MaidenNameTest()
        {
            // TODO unit test for the property 'MaidenName'
        }
        /// <summary>
        /// Test the property 'MaritalStatus'
        /// </summary>
        [Fact]
        public void MaritalStatusTest()
        {
            // TODO unit test for the property 'MaritalStatus'
        }
        /// <summary>
        /// Test the property 'OnHANIS'
        /// </summary>
        [Fact]
        public void OnHANISTest()
        {
            // TODO unit test for the property 'OnHANIS'
        }
        /// <summary>
        /// Test the property 'OnNPR'
        /// </summary>
        [Fact]
        public void OnNPRTest()
        {
            // TODO unit test for the property 'OnNPR'
        }
        /// <summary>
        /// Test the property 'Photo'
        /// </summary>
        [Fact]
        public void PhotoTest()
        {
            // TODO unit test for the property 'Photo'
        }
        /// <summary>
        /// Test the property 'SmartCardIssued'
        /// </summary>
        [Fact]
        public void SmartCardIssuedTest()
        {
            // TODO unit test for the property 'SmartCardIssued'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

    }

}
