/* tslint:disable */
/* eslint-disable */
/**
 * DOJAH APIs
 * Use Dojah to verify, onboard and manage user identity across Africa!
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * https://konfigthis.com
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { CreateWalletResponseEntity } from './create-wallet-response-entity';

/**
 * 
 * @export
 * @interface CreateWalletResponse
 */
export interface CreateWalletResponse {
    /**
     * 
     * @type {CreateWalletResponseEntity}
     * @memberof CreateWalletResponse
     */
    'entity'?: CreateWalletResponseEntity;
}

