/* tslint:disable */
/* eslint-disable */
/**
 * DOJAH Publilc APIs
 * Use Dojah to verify, onboard and manage user identity across Africa!
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { FraudGetEmailReputationResponseEntityBreachDetails } from './fraud-get-email-reputation-response-entity-breach-details';
// May contain unused imports in some cases
// @ts-ignore
import { FraudGetEmailReputationResponseEntityDetails } from './fraud-get-email-reputation-response-entity-details';
// May contain unused imports in some cases
// @ts-ignore
import { FraudGetEmailReputationResponseEntityDomainDetails } from './fraud-get-email-reputation-response-entity-domain-details';

/**
 * 
 * @export
 * @interface FraudGetEmailReputationResponseEntity
 */
export interface FraudGetEmailReputationResponseEntity {
    /**
     * 
     * @type {string}
     * @memberof FraudGetEmailReputationResponseEntity
     */
    'email'?: string;
    /**
     * 
     * @type {string}
     * @memberof FraudGetEmailReputationResponseEntity
     */
    'reputation'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof FraudGetEmailReputationResponseEntity
     */
    'suspicious'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof FraudGetEmailReputationResponseEntity
     */
    'references'?: number;
    /**
     * 
     * @type {FraudGetEmailReputationResponseEntityDetails}
     * @memberof FraudGetEmailReputationResponseEntity
     */
    'details'?: FraudGetEmailReputationResponseEntityDetails;
    /**
     * 
     * @type {number}
     * @memberof FraudGetEmailReputationResponseEntity
     */
    'score'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof FraudGetEmailReputationResponseEntity
     */
    'deliverable'?: boolean;
    /**
     * 
     * @type {FraudGetEmailReputationResponseEntityDomainDetails}
     * @memberof FraudGetEmailReputationResponseEntity
     */
    'domain_details'?: FraudGetEmailReputationResponseEntityDomainDetails;
    /**
     * 
     * @type {FraudGetEmailReputationResponseEntityBreachDetails}
     * @memberof FraudGetEmailReputationResponseEntity
     */
    'breach_details'?: FraudGetEmailReputationResponseEntityBreachDetails;
    /**
     * 
     * @type {Array<string>}
     * @memberof FraudGetEmailReputationResponseEntity
     */
    'account_details_registered'?: Array<string>;
}

