/* tslint:disable */
/* eslint-disable */
/**
 * DOJAH APIs
 * Use Dojah to verify, onboard and manage user identity across Africa!
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * https://konfigthis.com
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 * @interface GetDataPlansResponseEntityInner
 */
export interface GetDataPlansResponseEntityInner {
    /**
     * 
     * @type {string}
     * @memberof GetDataPlansResponseEntityInner
     */
    'description'?: string;
    /**
     * 
     * @type {number}
     * @memberof GetDataPlansResponseEntityInner
     */
    'amount'?: number;
    /**
     * 
     * @type {string}
     * @memberof GetDataPlansResponseEntityInner
     */
    'plan'?: string;
}

