/* tslint:disable */
/* eslint-disable */
/**
 * DOJAH APIs
 * Use Dojah to verify, onboard and manage user identity across Africa!
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * https://konfigthis.com
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { GetPassportResponseEntity } from './get-passport-response-entity';

/**
 * 
 * @export
 * @interface GetPassportResponse
 */
export interface GetPassportResponse {
    /**
     * 
     * @type {GetPassportResponseEntity}
     * @memberof GetPassportResponse
     */
    'entity'?: GetPassportResponseEntity;
}

