/* tslint:disable */
/* eslint-disable */
/**
 * DOJAH Publilc APIs
 * Use Dojah to verify, onboard and manage user identity across Africa!
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { KycSubmitAddressResponseEntityData } from './kyc-submit-address-response-entity-data';

/**
 * 
 * @export
 * @interface KycSubmitAddressResponseEntity
 */
export interface KycSubmitAddressResponseEntity {
    /**
     * 
     * @type {number}
     * @memberof KycSubmitAddressResponseEntity
     */
    'status'?: number;
    /**
     * 
     * @type {string}
     * @memberof KycSubmitAddressResponseEntity
     */
    'reference_id'?: string;
    /**
     * 
     * @type {KycSubmitAddressResponseEntityData}
     * @memberof KycSubmitAddressResponseEntity
     */
    'data'?: KycSubmitAddressResponseEntityData;
}

