/* tslint:disable */
/* eslint-disable */
/**
 * DOJAH APIs
 * Use Dojah to verify, onboard and manage user identity across Africa!
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * https://konfigthis.com
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 * @interface RequestSenderIdResponseEntityInner
 */
export interface RequestSenderIdResponseEntityInner {
    /**
     * 
     * @type {string}
     * @memberof RequestSenderIdResponseEntityInner
     */
    'sender_id'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof RequestSenderIdResponseEntityInner
     */
    'activated'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof RequestSenderIdResponseEntityInner
     */
    'createdAt'?: string;
}

