/* tslint:disable */
/* eslint-disable */
/**
 * DOJAH Publilc APIs
 * Use Dojah to verify, onboard and manage user identity across Africa!
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 * @interface ZwKycVerifyIdResponseEntity
 */
export interface ZwKycVerifyIdResponseEntity {
    /**
     * 
     * @type {string}
     * @memberof ZwKycVerifyIdResponseEntity
     */
    'person_no'?: string;
    /**
     * 
     * @type {string}
     * @memberof ZwKycVerifyIdResponseEntity
     */
    'status'?: string;
    /**
     * 
     * @type {string}
     * @memberof ZwKycVerifyIdResponseEntity
     */
    'surname'?: string;
    /**
     * 
     * @type {string}
     * @memberof ZwKycVerifyIdResponseEntity
     */
    'first_name'?: string;
    /**
     * 
     * @type {string}
     * @memberof ZwKycVerifyIdResponseEntity
     */
    'sex'?: string;
    /**
     * 
     * @type {string}
     * @memberof ZwKycVerifyIdResponseEntity
     */
    'date_of_birth'?: string;
    /**
     * 
     * @type {string}
     * @memberof ZwKycVerifyIdResponseEntity
     */
    'date_of_death'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ZwKycVerifyIdResponseEntity
     */
    'birth_place'?: string | null;
}

