/*
 * DOJAH APIs
 * Use Dojah to verify, onboard and manage user identity across Africa!
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package io.dojah.client.api;

import io.dojah.client.ApiException;
import io.dojah.client.model.AnalyzeDocumentResponse;
import io.dojah.client.model.GetBasicBvnResponse;
import io.dojah.client.model.GetBasicPhoneNumberResponse;
import io.dojah.client.model.GetEmailReputationResponse;
import io.dojah.client.model.GetFullBvnResponse;
import io.dojah.client.model.GetKycDriversLicenseResponse;
import io.dojah.client.model.GetKycPassportResponse;
import io.dojah.client.model.GetNubanResponse;
import io.dojah.client.model.GetPhoneNumber404Response;
import io.dojah.client.model.GetPhoneNumberResponse;
import io.dojah.client.model.GetPremiumBvnResponse;
import io.dojah.client.model.GetVinResponse;
import io.dojah.client.model.GetVninResponse;
import io.dojah.client.model.ValidateBvnResponse;
import io.dojah.client.model.VerifyAgeResponse;
import io.dojah.client.model.VerifySelfieBvnResponse;
import io.dojah.client.model.VerifySelfieNinResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for KycApi
 */
@Disabled
public class KycApiTest {

    private final KycApi api = new KycApi();

    /**
     * KYC - Document Analysis
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void analyzeDocumentTest() throws ApiException {
        AnalyzeDocumentResponse response = api.analyzeDocument();
        // TODO: test validations
    }

    /**
     * KYC - Get Basic BVN Info
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getBasicBvnTest() throws ApiException {
        Integer bvn = null;
        GetBasicBvnResponse response = api.getBasicBvn(bvn);
        // TODO: test validations
    }

    /**
     * KYC Lookup Phone Number Basic
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getBasicPhoneNumberTest() throws ApiException {
        Integer phoneNumber = null;
        GetBasicPhoneNumberResponse response = api.getBasicPhoneNumber(phoneNumber);
        // TODO: test validations
    }

    /**
     * KYC - Get Drivers License Info
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getDriversLicenseTest() throws ApiException {
        String licenseNumber = null;
        GetKycDriversLicenseResponse response = api.getDriversLicense(licenseNumber);
        // TODO: test validations
    }

    /**
     * KYC - Get Email Reputation
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getEmailReputationTest() throws ApiException {
        String email = null;
        GetEmailReputationResponse response = api.getEmailReputation(email);
        // TODO: test validations
    }

    /**
     * KYC - Lookup BVN Basic
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getFullBvnTest() throws ApiException {
        Integer bvn = null;
        GetFullBvnResponse response = api.getFullBvn(bvn);
        // TODO: test validations
    }

    /**
     * KYC - Get NUBAN Information
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getNubanTest() throws ApiException {
        Integer bankCode = null;
        Integer accountNumber = null;
        GetNubanResponse response = api.getNuban(bankCode, accountNumber);
        // TODO: test validations
    }

    /**
     * KYC - Passport
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getPassportTest() throws ApiException {
        Integer passportNumber = null;
        String surname = null;
        GetKycPassportResponse response = api.getPassport(passportNumber, surname);
        // TODO: test validations
    }

    /**
     * KYC - Lookup Phone Number
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getPhoneNumberTest() throws ApiException {
        Integer phoneNumber = null;
        GetPhoneNumberResponse response = api.getPhoneNumber(phoneNumber);
        // TODO: test validations
    }

    /**
     * KYC - Lookup BVN Premium
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getPremiumBvnTest() throws ApiException {
        Integer bvn = null;
        GetPremiumBvnResponse response = api.getPremiumBvn(bvn);
        // TODO: test validations
    }

    /**
     * KYC - Get VIN
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getVINTest() throws ApiException {
        String mode = null;
        String firstname = null;
        String lastname = null;
        Integer vin = null;
        String state = null;
        GetVinResponse response = api.getVIN(mode, firstname, lastname, vin, state);
        // TODO: test validations
    }

    /**
     * Lookup VNIN
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getVninTest() throws ApiException {
        String vnin = null;
        GetVninResponse response = api.getVnin(vnin);
        // TODO: test validations
    }

    /**
     * KYC - Validate BVN
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void validateBvnTest() throws ApiException {
        Integer bvn = null;
        String firstName = null;
        String dob = null;
        ValidateBvnResponse response = api.validateBvn(bvn, firstName, dob);
        // TODO: test validations
    }

    /**
     * KYC - Age Verification
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void verifyAgeTest() throws ApiException {
        String mode = null;
        Integer accountNumber = null;
        Integer bankCode = null;
        String dob = null;
        String firstName = null;
        String lastName = null;
        VerifyAgeResponse response = api.verifyAge(mode, accountNumber, bankCode, dob, firstName, lastName);
        // TODO: test validations
    }

    /**
     * KYC - Selfie BVN Verificatoin
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void verifySelfieBvnTest() throws ApiException {
        Object body = null;
        VerifySelfieBvnResponse response = api.verifySelfieBvn(body);
        // TODO: test validations
    }

    /**
     * KYC - Selfie NIN Verification
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void verifySelfieNinTest() throws ApiException {
        Object body = null;
        VerifySelfieNinResponse response = api.verifySelfieNin(body);
        // TODO: test validations
    }

}
