/*
 * DOJAH APIs
 *
 * Use Dojah to verify, onboard and manage user identity across Africa!
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://konfigthis.com
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Dojah.Net.Client;
using Dojah.Net.Api;
// uncomment below to import models
//using Dojah.Net.Model;

namespace Dojah.Net.Test.Api
{
    /// <summary>
    ///  Class for testing KEKYCApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Konfig (https://konfigthis.com).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class KEKYCApiTests : IDisposable
    {
        private KEKYCApi instance;

        public KEKYCApiTests()
        {
            instance = new KEKYCApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of KEKYCApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' KEKYCApi
            //Assert.IsType<KEKYCApi>(instance);
        }

        /// <summary>
        /// Test GetNationalId
        /// </summary>
        [Fact]
        public void GetNationalIdTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? id = null;
            //string firstName = null;
            //string lastName = null;
            //string middleName = null;
            //string dateOfBirth = null;
            //string gender = null;
            //var response = instance.GetNationalId(id, firstName, lastName, middleName, dateOfBirth, gender);
            //Assert.IsType<GetNationalIdResponse>(response);
        }
    }
}
