/*
DOJAH Publilc APIs

Use Dojah to verify, onboard and manage user identity across Africa!

API version: 1.0.0
*/

// Code generated by Konfig (https://konfigthis.com); DO NOT EDIT.

package dojah

import (
	"encoding/json"
)

// KybGetCacResponseEntity struct for KybGetCacResponseEntity
type KybGetCacResponseEntity struct {
	RcNumber *string `json:"rc_number,omitempty"`
	CompanyName *string `json:"company_name,omitempty"`
	Address *string `json:"address,omitempty"`
	DateOfRegistration *string `json:"date_of_registration,omitempty"`
}

// NewKybGetCacResponseEntity instantiates a new KybGetCacResponseEntity object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewKybGetCacResponseEntity() *KybGetCacResponseEntity {
	this := KybGetCacResponseEntity{}
	return &this
}

// NewKybGetCacResponseEntityWithDefaults instantiates a new KybGetCacResponseEntity object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewKybGetCacResponseEntityWithDefaults() *KybGetCacResponseEntity {
	this := KybGetCacResponseEntity{}
	return &this
}

// GetRcNumber returns the RcNumber field value if set, zero value otherwise.
func (o *KybGetCacResponseEntity) GetRcNumber() string {
	if o == nil || isNil(o.RcNumber) {
		var ret string
		return ret
	}
	return *o.RcNumber
}

// GetRcNumberOk returns a tuple with the RcNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KybGetCacResponseEntity) GetRcNumberOk() (*string, bool) {
	if o == nil || isNil(o.RcNumber) {
    return nil, false
	}
	return o.RcNumber, true
}

// HasRcNumber returns a boolean if a field has been set.
func (o *KybGetCacResponseEntity) HasRcNumber() bool {
	if o != nil && !isNil(o.RcNumber) {
		return true
	}

	return false
}

// SetRcNumber gets a reference to the given string and assigns it to the RcNumber field.
func (o *KybGetCacResponseEntity) SetRcNumber(v string) {
	o.RcNumber = &v
}

// GetCompanyName returns the CompanyName field value if set, zero value otherwise.
func (o *KybGetCacResponseEntity) GetCompanyName() string {
	if o == nil || isNil(o.CompanyName) {
		var ret string
		return ret
	}
	return *o.CompanyName
}

// GetCompanyNameOk returns a tuple with the CompanyName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KybGetCacResponseEntity) GetCompanyNameOk() (*string, bool) {
	if o == nil || isNil(o.CompanyName) {
    return nil, false
	}
	return o.CompanyName, true
}

// HasCompanyName returns a boolean if a field has been set.
func (o *KybGetCacResponseEntity) HasCompanyName() bool {
	if o != nil && !isNil(o.CompanyName) {
		return true
	}

	return false
}

// SetCompanyName gets a reference to the given string and assigns it to the CompanyName field.
func (o *KybGetCacResponseEntity) SetCompanyName(v string) {
	o.CompanyName = &v
}

// GetAddress returns the Address field value if set, zero value otherwise.
func (o *KybGetCacResponseEntity) GetAddress() string {
	if o == nil || isNil(o.Address) {
		var ret string
		return ret
	}
	return *o.Address
}

// GetAddressOk returns a tuple with the Address field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KybGetCacResponseEntity) GetAddressOk() (*string, bool) {
	if o == nil || isNil(o.Address) {
    return nil, false
	}
	return o.Address, true
}

// HasAddress returns a boolean if a field has been set.
func (o *KybGetCacResponseEntity) HasAddress() bool {
	if o != nil && !isNil(o.Address) {
		return true
	}

	return false
}

// SetAddress gets a reference to the given string and assigns it to the Address field.
func (o *KybGetCacResponseEntity) SetAddress(v string) {
	o.Address = &v
}

// GetDateOfRegistration returns the DateOfRegistration field value if set, zero value otherwise.
func (o *KybGetCacResponseEntity) GetDateOfRegistration() string {
	if o == nil || isNil(o.DateOfRegistration) {
		var ret string
		return ret
	}
	return *o.DateOfRegistration
}

// GetDateOfRegistrationOk returns a tuple with the DateOfRegistration field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KybGetCacResponseEntity) GetDateOfRegistrationOk() (*string, bool) {
	if o == nil || isNil(o.DateOfRegistration) {
    return nil, false
	}
	return o.DateOfRegistration, true
}

// HasDateOfRegistration returns a boolean if a field has been set.
func (o *KybGetCacResponseEntity) HasDateOfRegistration() bool {
	if o != nil && !isNil(o.DateOfRegistration) {
		return true
	}

	return false
}

// SetDateOfRegistration gets a reference to the given string and assigns it to the DateOfRegistration field.
func (o *KybGetCacResponseEntity) SetDateOfRegistration(v string) {
	o.DateOfRegistration = &v
}

func (o KybGetCacResponseEntity) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.RcNumber) {
		toSerialize["rc_number"] = o.RcNumber
	}
	if !isNil(o.CompanyName) {
		toSerialize["company_name"] = o.CompanyName
	}
	if !isNil(o.Address) {
		toSerialize["address"] = o.Address
	}
	if !isNil(o.DateOfRegistration) {
		toSerialize["date_of_registration"] = o.DateOfRegistration
	}
	return json.Marshal(toSerialize)
}

type NullableKybGetCacResponseEntity struct {
	value *KybGetCacResponseEntity
	isSet bool
}

func (v NullableKybGetCacResponseEntity) Get() *KybGetCacResponseEntity {
	return v.value
}

func (v *NullableKybGetCacResponseEntity) Set(val *KybGetCacResponseEntity) {
	v.value = val
	v.isSet = true
}

func (v NullableKybGetCacResponseEntity) IsSet() bool {
	return v.isSet
}

func (v *NullableKybGetCacResponseEntity) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableKybGetCacResponseEntity(val *KybGetCacResponseEntity) *NullableKybGetCacResponseEntity {
	return &NullableKybGetCacResponseEntity{value: val, isSet: true}
}

func (v NullableKybGetCacResponseEntity) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableKybGetCacResponseEntity) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


