/*
DOJAH Publilc APIs

Use Dojah to verify, onboard and manage user identity across Africa!

API version: 1.0.0
*/

// Code generated by Konfig (https://konfigthis.com); DO NOT EDIT.

package dojah

import (
	"encoding/json"
)

// GetVninResponse struct for GetVninResponse
type GetVninResponse struct {
	Entity *GetVninResponseEntity `json:"entity,omitempty"`
}

// NewGetVninResponse instantiates a new GetVninResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetVninResponse() *GetVninResponse {
	this := GetVninResponse{}
	return &this
}

// NewGetVninResponseWithDefaults instantiates a new GetVninResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetVninResponseWithDefaults() *GetVninResponse {
	this := GetVninResponse{}
	return &this
}

// GetEntity returns the Entity field value if set, zero value otherwise.
func (o *GetVninResponse) GetEntity() GetVninResponseEntity {
	if o == nil || isNil(o.Entity) {
		var ret GetVninResponseEntity
		return ret
	}
	return *o.Entity
}

// GetEntityOk returns a tuple with the Entity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetVninResponse) GetEntityOk() (*GetVninResponseEntity, bool) {
	if o == nil || isNil(o.Entity) {
    return nil, false
	}
	return o.Entity, true
}

// HasEntity returns a boolean if a field has been set.
func (o *GetVninResponse) HasEntity() bool {
	if o != nil && !isNil(o.Entity) {
		return true
	}

	return false
}

// SetEntity gets a reference to the given GetVninResponseEntity and assigns it to the Entity field.
func (o *GetVninResponse) SetEntity(v GetVninResponseEntity) {
	o.Entity = &v
}

func (o GetVninResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Entity) {
		toSerialize["entity"] = o.Entity
	}
	return json.Marshal(toSerialize)
}

type NullableGetVninResponse struct {
	value *GetVninResponse
	isSet bool
}

func (v NullableGetVninResponse) Get() *GetVninResponse {
	return v.value
}

func (v *NullableGetVninResponse) Set(val *GetVninResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetVninResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetVninResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetVninResponse(val *GetVninResponse) *NullableGetVninResponse {
	return &NullableGetVninResponse{value: val, isSet: true}
}

func (v NullableGetVninResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetVninResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


