/*
DOJAH APIs

Use Dojah to verify, onboard and manage user identity across Africa!

API version: 1.0.0
*/

// Code generated by Konfig (https://konfigthis.com); DO NOT EDIT.

package dojah

import (
	"encoding/json"
)

// CollectStatusFromPdfResponseEntity struct for CollectStatusFromPdfResponseEntity
type CollectStatusFromPdfResponseEntity struct {
	AccountId *string `json:"account_id,omitempty"`
}

// NewCollectStatusFromPdfResponseEntity instantiates a new CollectStatusFromPdfResponseEntity object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCollectStatusFromPdfResponseEntity() *CollectStatusFromPdfResponseEntity {
	this := CollectStatusFromPdfResponseEntity{}
	return &this
}

// NewCollectStatusFromPdfResponseEntityWithDefaults instantiates a new CollectStatusFromPdfResponseEntity object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCollectStatusFromPdfResponseEntityWithDefaults() *CollectStatusFromPdfResponseEntity {
	this := CollectStatusFromPdfResponseEntity{}
	return &this
}

// GetAccountId returns the AccountId field value if set, zero value otherwise.
func (o *CollectStatusFromPdfResponseEntity) GetAccountId() string {
	if o == nil || isNil(o.AccountId) {
		var ret string
		return ret
	}
	return *o.AccountId
}

// GetAccountIdOk returns a tuple with the AccountId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CollectStatusFromPdfResponseEntity) GetAccountIdOk() (*string, bool) {
	if o == nil || isNil(o.AccountId) {
    return nil, false
	}
	return o.AccountId, true
}

// HasAccountId returns a boolean if a field has been set.
func (o *CollectStatusFromPdfResponseEntity) HasAccountId() bool {
	if o != nil && !isNil(o.AccountId) {
		return true
	}

	return false
}

// SetAccountId gets a reference to the given string and assigns it to the AccountId field.
func (o *CollectStatusFromPdfResponseEntity) SetAccountId(v string) {
	o.AccountId = &v
}

func (o CollectStatusFromPdfResponseEntity) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.AccountId) {
		toSerialize["account_id"] = o.AccountId
	}
	return json.Marshal(toSerialize)
}

type NullableCollectStatusFromPdfResponseEntity struct {
	value *CollectStatusFromPdfResponseEntity
	isSet bool
}

func (v NullableCollectStatusFromPdfResponseEntity) Get() *CollectStatusFromPdfResponseEntity {
	return v.value
}

func (v *NullableCollectStatusFromPdfResponseEntity) Set(val *CollectStatusFromPdfResponseEntity) {
	v.value = val
	v.isSet = true
}

func (v NullableCollectStatusFromPdfResponseEntity) IsSet() bool {
	return v.isSet
}

func (v *NullableCollectStatusFromPdfResponseEntity) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCollectStatusFromPdfResponseEntity(val *CollectStatusFromPdfResponseEntity) *NullableCollectStatusFromPdfResponseEntity {
	return &NullableCollectStatusFromPdfResponseEntity{value: val, isSet: true}
}

func (v NullableCollectStatusFromPdfResponseEntity) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCollectStatusFromPdfResponseEntity) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


