/*
DOJAH Publilc APIs

Use Dojah to verify, onboard and manage user identity across Africa!

API version: 1.0.0
*/

// Code generated by Konfig (https://konfigthis.com); DO NOT EDIT.

package dojah

import (
	"encoding/json"
)

// SendSmsResponse struct for SendSmsResponse
type SendSmsResponse struct {
	Entity *SendSmsResponseEntity `json:"entity,omitempty"`
}

// NewSendSmsResponse instantiates a new SendSmsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSendSmsResponse() *SendSmsResponse {
	this := SendSmsResponse{}
	return &this
}

// NewSendSmsResponseWithDefaults instantiates a new SendSmsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSendSmsResponseWithDefaults() *SendSmsResponse {
	this := SendSmsResponse{}
	return &this
}

// GetEntity returns the Entity field value if set, zero value otherwise.
func (o *SendSmsResponse) GetEntity() SendSmsResponseEntity {
	if o == nil || isNil(o.Entity) {
		var ret SendSmsResponseEntity
		return ret
	}
	return *o.Entity
}

// GetEntityOk returns a tuple with the Entity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SendSmsResponse) GetEntityOk() (*SendSmsResponseEntity, bool) {
	if o == nil || isNil(o.Entity) {
    return nil, false
	}
	return o.Entity, true
}

// HasEntity returns a boolean if a field has been set.
func (o *SendSmsResponse) HasEntity() bool {
	if o != nil && !isNil(o.Entity) {
		return true
	}

	return false
}

// SetEntity gets a reference to the given SendSmsResponseEntity and assigns it to the Entity field.
func (o *SendSmsResponse) SetEntity(v SendSmsResponseEntity) {
	o.Entity = &v
}

func (o SendSmsResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Entity) {
		toSerialize["entity"] = o.Entity
	}
	return json.Marshal(toSerialize)
}

type NullableSendSmsResponse struct {
	value *SendSmsResponse
	isSet bool
}

func (v NullableSendSmsResponse) Get() *SendSmsResponse {
	return v.value
}

func (v *NullableSendSmsResponse) Set(val *SendSmsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableSendSmsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableSendSmsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSendSmsResponse(val *SendSmsResponse) *NullableSendSmsResponse {
	return &NullableSendSmsResponse{value: val, isSet: true}
}

func (v NullableSendSmsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSendSmsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


