/*
DOJAH APIs

Use Dojah to verify, onboard and manage user identity across Africa!

API version: 1.0.0
*/

// Code generated by Konfig (https://konfigthis.com); DO NOT EDIT.

package dojah

import (
	"encoding/json"
)

// GetGenericOcrTextResponseEntity struct for GetGenericOcrTextResponseEntity
type GetGenericOcrTextResponseEntity struct {
	Data []string `json:"data,omitempty"`
}

// NewGetGenericOcrTextResponseEntity instantiates a new GetGenericOcrTextResponseEntity object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetGenericOcrTextResponseEntity() *GetGenericOcrTextResponseEntity {
	this := GetGenericOcrTextResponseEntity{}
	return &this
}

// NewGetGenericOcrTextResponseEntityWithDefaults instantiates a new GetGenericOcrTextResponseEntity object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetGenericOcrTextResponseEntityWithDefaults() *GetGenericOcrTextResponseEntity {
	this := GetGenericOcrTextResponseEntity{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *GetGenericOcrTextResponseEntity) GetData() []string {
	if o == nil || isNil(o.Data) {
		var ret []string
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetGenericOcrTextResponseEntity) GetDataOk() ([]string, bool) {
	if o == nil || isNil(o.Data) {
    return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *GetGenericOcrTextResponseEntity) HasData() bool {
	if o != nil && !isNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []string and assigns it to the Data field.
func (o *GetGenericOcrTextResponseEntity) SetData(v []string) {
	o.Data = v
}

func (o GetGenericOcrTextResponseEntity) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return json.Marshal(toSerialize)
}

type NullableGetGenericOcrTextResponseEntity struct {
	value *GetGenericOcrTextResponseEntity
	isSet bool
}

func (v NullableGetGenericOcrTextResponseEntity) Get() *GetGenericOcrTextResponseEntity {
	return v.value
}

func (v *NullableGetGenericOcrTextResponseEntity) Set(val *GetGenericOcrTextResponseEntity) {
	v.value = val
	v.isSet = true
}

func (v NullableGetGenericOcrTextResponseEntity) IsSet() bool {
	return v.isSet
}

func (v *NullableGetGenericOcrTextResponseEntity) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetGenericOcrTextResponseEntity(val *GetGenericOcrTextResponseEntity) *NullableGetGenericOcrTextResponseEntity {
	return &NullableGetGenericOcrTextResponseEntity{value: val, isSet: true}
}

func (v NullableGetGenericOcrTextResponseEntity) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetGenericOcrTextResponseEntity) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


