/*
DOJAH APIs

Use Dojah to verify, onboard and manage user identity across Africa!

API version: 1.0.0
*/

// Code generated by Konfig (https://konfigthis.com); DO NOT EDIT.

package dojah

import (
	"encoding/json"
)

// GetAccountSubscriptionsResponse struct for GetAccountSubscriptionsResponse
type GetAccountSubscriptionsResponse struct {
	Entity *GetAccountSubscriptionsResponseEntity `json:"entity,omitempty"`
}

// NewGetAccountSubscriptionsResponse instantiates a new GetAccountSubscriptionsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetAccountSubscriptionsResponse() *GetAccountSubscriptionsResponse {
	this := GetAccountSubscriptionsResponse{}
	return &this
}

// NewGetAccountSubscriptionsResponseWithDefaults instantiates a new GetAccountSubscriptionsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetAccountSubscriptionsResponseWithDefaults() *GetAccountSubscriptionsResponse {
	this := GetAccountSubscriptionsResponse{}
	return &this
}

// GetEntity returns the Entity field value if set, zero value otherwise.
func (o *GetAccountSubscriptionsResponse) GetEntity() GetAccountSubscriptionsResponseEntity {
	if o == nil || isNil(o.Entity) {
		var ret GetAccountSubscriptionsResponseEntity
		return ret
	}
	return *o.Entity
}

// GetEntityOk returns a tuple with the Entity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAccountSubscriptionsResponse) GetEntityOk() (*GetAccountSubscriptionsResponseEntity, bool) {
	if o == nil || isNil(o.Entity) {
    return nil, false
	}
	return o.Entity, true
}

// HasEntity returns a boolean if a field has been set.
func (o *GetAccountSubscriptionsResponse) HasEntity() bool {
	if o != nil && !isNil(o.Entity) {
		return true
	}

	return false
}

// SetEntity gets a reference to the given GetAccountSubscriptionsResponseEntity and assigns it to the Entity field.
func (o *GetAccountSubscriptionsResponse) SetEntity(v GetAccountSubscriptionsResponseEntity) {
	o.Entity = &v
}

func (o GetAccountSubscriptionsResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Entity) {
		toSerialize["entity"] = o.Entity
	}
	return json.Marshal(toSerialize)
}

type NullableGetAccountSubscriptionsResponse struct {
	value *GetAccountSubscriptionsResponse
	isSet bool
}

func (v NullableGetAccountSubscriptionsResponse) Get() *GetAccountSubscriptionsResponse {
	return v.value
}

func (v *NullableGetAccountSubscriptionsResponse) Set(val *GetAccountSubscriptionsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetAccountSubscriptionsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetAccountSubscriptionsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetAccountSubscriptionsResponse(val *GetAccountSubscriptionsResponse) *NullableGetAccountSubscriptionsResponse {
	return &NullableGetAccountSubscriptionsResponse{value: val, isSet: true}
}

func (v NullableGetAccountSubscriptionsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetAccountSubscriptionsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


