/*
DOJAH APIs

Use Dojah to verify, onboard and manage user identity across Africa!

API version: 1.0.0
*/

// Code generated by Konfig (https://konfigthis.com); DO NOT EDIT.

package dojah

import (
	"encoding/json"
)

// GetAccountAnalysisResponseEntity struct for GetAccountAnalysisResponseEntity
type GetAccountAnalysisResponseEntity struct {
	AccountBreakdown *GetAccountAnalysisResponseEntityAccountBreakdown `json:"accountBreakdown,omitempty"`
	ExpenseBreakdown *GetAccountAnalysisResponseEntityExpenseBreakdown `json:"expenseBreakdown,omitempty"`
	FundsManagement *GetAccountAnalysisResponseEntityFundsManagement `json:"fundsManagement,omitempty"`
	InflowBreakdown *GetAccountAnalysisResponseEntityInflowBreakdown `json:"inflowBreakdown,omitempty"`
	TransactionRoutineBreakdown *GetAccountAnalysisResponseEntityTransactionRoutineBreakdown `json:"transactionRoutineBreakdown,omitempty"`
	Status *float32 `json:"status,omitempty"`
}

// NewGetAccountAnalysisResponseEntity instantiates a new GetAccountAnalysisResponseEntity object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetAccountAnalysisResponseEntity() *GetAccountAnalysisResponseEntity {
	this := GetAccountAnalysisResponseEntity{}
	return &this
}

// NewGetAccountAnalysisResponseEntityWithDefaults instantiates a new GetAccountAnalysisResponseEntity object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetAccountAnalysisResponseEntityWithDefaults() *GetAccountAnalysisResponseEntity {
	this := GetAccountAnalysisResponseEntity{}
	return &this
}

// GetAccountBreakdown returns the AccountBreakdown field value if set, zero value otherwise.
func (o *GetAccountAnalysisResponseEntity) GetAccountBreakdown() GetAccountAnalysisResponseEntityAccountBreakdown {
	if o == nil || isNil(o.AccountBreakdown) {
		var ret GetAccountAnalysisResponseEntityAccountBreakdown
		return ret
	}
	return *o.AccountBreakdown
}

// GetAccountBreakdownOk returns a tuple with the AccountBreakdown field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAccountAnalysisResponseEntity) GetAccountBreakdownOk() (*GetAccountAnalysisResponseEntityAccountBreakdown, bool) {
	if o == nil || isNil(o.AccountBreakdown) {
    return nil, false
	}
	return o.AccountBreakdown, true
}

// HasAccountBreakdown returns a boolean if a field has been set.
func (o *GetAccountAnalysisResponseEntity) HasAccountBreakdown() bool {
	if o != nil && !isNil(o.AccountBreakdown) {
		return true
	}

	return false
}

// SetAccountBreakdown gets a reference to the given GetAccountAnalysisResponseEntityAccountBreakdown and assigns it to the AccountBreakdown field.
func (o *GetAccountAnalysisResponseEntity) SetAccountBreakdown(v GetAccountAnalysisResponseEntityAccountBreakdown) {
	o.AccountBreakdown = &v
}

// GetExpenseBreakdown returns the ExpenseBreakdown field value if set, zero value otherwise.
func (o *GetAccountAnalysisResponseEntity) GetExpenseBreakdown() GetAccountAnalysisResponseEntityExpenseBreakdown {
	if o == nil || isNil(o.ExpenseBreakdown) {
		var ret GetAccountAnalysisResponseEntityExpenseBreakdown
		return ret
	}
	return *o.ExpenseBreakdown
}

// GetExpenseBreakdownOk returns a tuple with the ExpenseBreakdown field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAccountAnalysisResponseEntity) GetExpenseBreakdownOk() (*GetAccountAnalysisResponseEntityExpenseBreakdown, bool) {
	if o == nil || isNil(o.ExpenseBreakdown) {
    return nil, false
	}
	return o.ExpenseBreakdown, true
}

// HasExpenseBreakdown returns a boolean if a field has been set.
func (o *GetAccountAnalysisResponseEntity) HasExpenseBreakdown() bool {
	if o != nil && !isNil(o.ExpenseBreakdown) {
		return true
	}

	return false
}

// SetExpenseBreakdown gets a reference to the given GetAccountAnalysisResponseEntityExpenseBreakdown and assigns it to the ExpenseBreakdown field.
func (o *GetAccountAnalysisResponseEntity) SetExpenseBreakdown(v GetAccountAnalysisResponseEntityExpenseBreakdown) {
	o.ExpenseBreakdown = &v
}

// GetFundsManagement returns the FundsManagement field value if set, zero value otherwise.
func (o *GetAccountAnalysisResponseEntity) GetFundsManagement() GetAccountAnalysisResponseEntityFundsManagement {
	if o == nil || isNil(o.FundsManagement) {
		var ret GetAccountAnalysisResponseEntityFundsManagement
		return ret
	}
	return *o.FundsManagement
}

// GetFundsManagementOk returns a tuple with the FundsManagement field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAccountAnalysisResponseEntity) GetFundsManagementOk() (*GetAccountAnalysisResponseEntityFundsManagement, bool) {
	if o == nil || isNil(o.FundsManagement) {
    return nil, false
	}
	return o.FundsManagement, true
}

// HasFundsManagement returns a boolean if a field has been set.
func (o *GetAccountAnalysisResponseEntity) HasFundsManagement() bool {
	if o != nil && !isNil(o.FundsManagement) {
		return true
	}

	return false
}

// SetFundsManagement gets a reference to the given GetAccountAnalysisResponseEntityFundsManagement and assigns it to the FundsManagement field.
func (o *GetAccountAnalysisResponseEntity) SetFundsManagement(v GetAccountAnalysisResponseEntityFundsManagement) {
	o.FundsManagement = &v
}

// GetInflowBreakdown returns the InflowBreakdown field value if set, zero value otherwise.
func (o *GetAccountAnalysisResponseEntity) GetInflowBreakdown() GetAccountAnalysisResponseEntityInflowBreakdown {
	if o == nil || isNil(o.InflowBreakdown) {
		var ret GetAccountAnalysisResponseEntityInflowBreakdown
		return ret
	}
	return *o.InflowBreakdown
}

// GetInflowBreakdownOk returns a tuple with the InflowBreakdown field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAccountAnalysisResponseEntity) GetInflowBreakdownOk() (*GetAccountAnalysisResponseEntityInflowBreakdown, bool) {
	if o == nil || isNil(o.InflowBreakdown) {
    return nil, false
	}
	return o.InflowBreakdown, true
}

// HasInflowBreakdown returns a boolean if a field has been set.
func (o *GetAccountAnalysisResponseEntity) HasInflowBreakdown() bool {
	if o != nil && !isNil(o.InflowBreakdown) {
		return true
	}

	return false
}

// SetInflowBreakdown gets a reference to the given GetAccountAnalysisResponseEntityInflowBreakdown and assigns it to the InflowBreakdown field.
func (o *GetAccountAnalysisResponseEntity) SetInflowBreakdown(v GetAccountAnalysisResponseEntityInflowBreakdown) {
	o.InflowBreakdown = &v
}

// GetTransactionRoutineBreakdown returns the TransactionRoutineBreakdown field value if set, zero value otherwise.
func (o *GetAccountAnalysisResponseEntity) GetTransactionRoutineBreakdown() GetAccountAnalysisResponseEntityTransactionRoutineBreakdown {
	if o == nil || isNil(o.TransactionRoutineBreakdown) {
		var ret GetAccountAnalysisResponseEntityTransactionRoutineBreakdown
		return ret
	}
	return *o.TransactionRoutineBreakdown
}

// GetTransactionRoutineBreakdownOk returns a tuple with the TransactionRoutineBreakdown field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAccountAnalysisResponseEntity) GetTransactionRoutineBreakdownOk() (*GetAccountAnalysisResponseEntityTransactionRoutineBreakdown, bool) {
	if o == nil || isNil(o.TransactionRoutineBreakdown) {
    return nil, false
	}
	return o.TransactionRoutineBreakdown, true
}

// HasTransactionRoutineBreakdown returns a boolean if a field has been set.
func (o *GetAccountAnalysisResponseEntity) HasTransactionRoutineBreakdown() bool {
	if o != nil && !isNil(o.TransactionRoutineBreakdown) {
		return true
	}

	return false
}

// SetTransactionRoutineBreakdown gets a reference to the given GetAccountAnalysisResponseEntityTransactionRoutineBreakdown and assigns it to the TransactionRoutineBreakdown field.
func (o *GetAccountAnalysisResponseEntity) SetTransactionRoutineBreakdown(v GetAccountAnalysisResponseEntityTransactionRoutineBreakdown) {
	o.TransactionRoutineBreakdown = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *GetAccountAnalysisResponseEntity) GetStatus() float32 {
	if o == nil || isNil(o.Status) {
		var ret float32
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAccountAnalysisResponseEntity) GetStatusOk() (*float32, bool) {
	if o == nil || isNil(o.Status) {
    return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *GetAccountAnalysisResponseEntity) HasStatus() bool {
	if o != nil && !isNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given float32 and assigns it to the Status field.
func (o *GetAccountAnalysisResponseEntity) SetStatus(v float32) {
	o.Status = &v
}

func (o GetAccountAnalysisResponseEntity) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.AccountBreakdown) {
		toSerialize["accountBreakdown"] = o.AccountBreakdown
	}
	if !isNil(o.ExpenseBreakdown) {
		toSerialize["expenseBreakdown"] = o.ExpenseBreakdown
	}
	if !isNil(o.FundsManagement) {
		toSerialize["fundsManagement"] = o.FundsManagement
	}
	if !isNil(o.InflowBreakdown) {
		toSerialize["inflowBreakdown"] = o.InflowBreakdown
	}
	if !isNil(o.TransactionRoutineBreakdown) {
		toSerialize["transactionRoutineBreakdown"] = o.TransactionRoutineBreakdown
	}
	if !isNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	return json.Marshal(toSerialize)
}

type NullableGetAccountAnalysisResponseEntity struct {
	value *GetAccountAnalysisResponseEntity
	isSet bool
}

func (v NullableGetAccountAnalysisResponseEntity) Get() *GetAccountAnalysisResponseEntity {
	return v.value
}

func (v *NullableGetAccountAnalysisResponseEntity) Set(val *GetAccountAnalysisResponseEntity) {
	v.value = val
	v.isSet = true
}

func (v NullableGetAccountAnalysisResponseEntity) IsSet() bool {
	return v.isSet
}

func (v *NullableGetAccountAnalysisResponseEntity) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetAccountAnalysisResponseEntity(val *GetAccountAnalysisResponseEntity) *NullableGetAccountAnalysisResponseEntity {
	return &NullableGetAccountAnalysisResponseEntity{value: val, isSet: true}
}

func (v NullableGetAccountAnalysisResponseEntity) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetAccountAnalysisResponseEntity) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


