/*
DOJAH APIs

Use Dojah to verify, onboard and manage user identity across Africa!

API version: 1.0.0
*/

// Code generated by Konfig (https://konfigthis.com); DO NOT EDIT.

package dojah

import (
	"encoding/json"
)

// CreateWalletResponseEntity struct for CreateWalletResponseEntity
type CreateWalletResponseEntity struct {
	WalletId *string `json:"wallet_id,omitempty"`
	WalletAmount *float32 `json:"wallet_amount,omitempty"`
	AccountNumber *string `json:"account_number,omitempty"`
	PhoneNumber *string `json:"phone_number,omitempty"`
}

// NewCreateWalletResponseEntity instantiates a new CreateWalletResponseEntity object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateWalletResponseEntity() *CreateWalletResponseEntity {
	this := CreateWalletResponseEntity{}
	return &this
}

// NewCreateWalletResponseEntityWithDefaults instantiates a new CreateWalletResponseEntity object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateWalletResponseEntityWithDefaults() *CreateWalletResponseEntity {
	this := CreateWalletResponseEntity{}
	return &this
}

// GetWalletId returns the WalletId field value if set, zero value otherwise.
func (o *CreateWalletResponseEntity) GetWalletId() string {
	if o == nil || isNil(o.WalletId) {
		var ret string
		return ret
	}
	return *o.WalletId
}

// GetWalletIdOk returns a tuple with the WalletId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateWalletResponseEntity) GetWalletIdOk() (*string, bool) {
	if o == nil || isNil(o.WalletId) {
    return nil, false
	}
	return o.WalletId, true
}

// HasWalletId returns a boolean if a field has been set.
func (o *CreateWalletResponseEntity) HasWalletId() bool {
	if o != nil && !isNil(o.WalletId) {
		return true
	}

	return false
}

// SetWalletId gets a reference to the given string and assigns it to the WalletId field.
func (o *CreateWalletResponseEntity) SetWalletId(v string) {
	o.WalletId = &v
}

// GetWalletAmount returns the WalletAmount field value if set, zero value otherwise.
func (o *CreateWalletResponseEntity) GetWalletAmount() float32 {
	if o == nil || isNil(o.WalletAmount) {
		var ret float32
		return ret
	}
	return *o.WalletAmount
}

// GetWalletAmountOk returns a tuple with the WalletAmount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateWalletResponseEntity) GetWalletAmountOk() (*float32, bool) {
	if o == nil || isNil(o.WalletAmount) {
    return nil, false
	}
	return o.WalletAmount, true
}

// HasWalletAmount returns a boolean if a field has been set.
func (o *CreateWalletResponseEntity) HasWalletAmount() bool {
	if o != nil && !isNil(o.WalletAmount) {
		return true
	}

	return false
}

// SetWalletAmount gets a reference to the given float32 and assigns it to the WalletAmount field.
func (o *CreateWalletResponseEntity) SetWalletAmount(v float32) {
	o.WalletAmount = &v
}

// GetAccountNumber returns the AccountNumber field value if set, zero value otherwise.
func (o *CreateWalletResponseEntity) GetAccountNumber() string {
	if o == nil || isNil(o.AccountNumber) {
		var ret string
		return ret
	}
	return *o.AccountNumber
}

// GetAccountNumberOk returns a tuple with the AccountNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateWalletResponseEntity) GetAccountNumberOk() (*string, bool) {
	if o == nil || isNil(o.AccountNumber) {
    return nil, false
	}
	return o.AccountNumber, true
}

// HasAccountNumber returns a boolean if a field has been set.
func (o *CreateWalletResponseEntity) HasAccountNumber() bool {
	if o != nil && !isNil(o.AccountNumber) {
		return true
	}

	return false
}

// SetAccountNumber gets a reference to the given string and assigns it to the AccountNumber field.
func (o *CreateWalletResponseEntity) SetAccountNumber(v string) {
	o.AccountNumber = &v
}

// GetPhoneNumber returns the PhoneNumber field value if set, zero value otherwise.
func (o *CreateWalletResponseEntity) GetPhoneNumber() string {
	if o == nil || isNil(o.PhoneNumber) {
		var ret string
		return ret
	}
	return *o.PhoneNumber
}

// GetPhoneNumberOk returns a tuple with the PhoneNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateWalletResponseEntity) GetPhoneNumberOk() (*string, bool) {
	if o == nil || isNil(o.PhoneNumber) {
    return nil, false
	}
	return o.PhoneNumber, true
}

// HasPhoneNumber returns a boolean if a field has been set.
func (o *CreateWalletResponseEntity) HasPhoneNumber() bool {
	if o != nil && !isNil(o.PhoneNumber) {
		return true
	}

	return false
}

// SetPhoneNumber gets a reference to the given string and assigns it to the PhoneNumber field.
func (o *CreateWalletResponseEntity) SetPhoneNumber(v string) {
	o.PhoneNumber = &v
}

func (o CreateWalletResponseEntity) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.WalletId) {
		toSerialize["wallet_id"] = o.WalletId
	}
	if !isNil(o.WalletAmount) {
		toSerialize["wallet_amount"] = o.WalletAmount
	}
	if !isNil(o.AccountNumber) {
		toSerialize["account_number"] = o.AccountNumber
	}
	if !isNil(o.PhoneNumber) {
		toSerialize["phone_number"] = o.PhoneNumber
	}
	return json.Marshal(toSerialize)
}

type NullableCreateWalletResponseEntity struct {
	value *CreateWalletResponseEntity
	isSet bool
}

func (v NullableCreateWalletResponseEntity) Get() *CreateWalletResponseEntity {
	return v.value
}

func (v *NullableCreateWalletResponseEntity) Set(val *CreateWalletResponseEntity) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateWalletResponseEntity) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateWalletResponseEntity) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateWalletResponseEntity(val *CreateWalletResponseEntity) *NullableCreateWalletResponseEntity {
	return &NullableCreateWalletResponseEntity{value: val, isSet: true}
}

func (v NullableCreateWalletResponseEntity) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateWalletResponseEntity) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


