/*
DOJAH APIs

Use Dojah to verify, onboard and manage user identity across Africa!

API version: 1.0.0
*/

// Code generated by Konfig (https://konfigthis.com); DO NOT EDIT.

package dojah

import (
	"encoding/json"
)

// VerifySelfieNinResponseEntity struct for VerifySelfieNinResponseEntity
type VerifySelfieNinResponseEntity struct {
	Title *string `json:"title,omitempty"`
	Nin *string `json:"nin,omitempty"`
	Firstname *string `json:"firstname,omitempty"`
	Middlename *string `json:"middlename,omitempty"`
	Surname *string `json:"surname,omitempty"`
	Maidenname *string `json:"maidenname,omitempty"`
	Telephoneno *string `json:"telephoneno,omitempty"`
	State *string `json:"state,omitempty"`
	Place *string `json:"place,omitempty"`
	Profession *string `json:"profession,omitempty"`
	Height *string `json:"height,omitempty"`
	Email *string `json:"email,omitempty"`
	Birthdate *string `json:"birthdate,omitempty"`
	Birthstate *string `json:"birthstate,omitempty"`
	Birthcountry *string `json:"birthcountry,omitempty"`
	CentralID *string `json:"centralID,omitempty"`
	Documentno *string `json:"documentno,omitempty"`
	Educationallevel *string `json:"educationallevel,omitempty"`
	Employmentstatus *string `json:"employmentstatus,omitempty"`
	NokFirstname *string `json:"nok_firstname,omitempty"`
	NokLastname *string `json:"nok_lastname,omitempty"`
	NokMiddlename *string `json:"nok_middlename,omitempty"`
	NokAddress1 *string `json:"nok_address1,omitempty"`
	NokAddress2 *string `json:"nok_address2,omitempty"`
	NokLga *string `json:"nok_lga,omitempty"`
	NokState *string `json:"nok_state,omitempty"`
	NokTown *string `json:"nok_town,omitempty"`
	NokPostalcode *string `json:"nok_postalcode,omitempty"`
	Othername *string `json:"othername,omitempty"`
	Pfirstname *string `json:"pfirstname,omitempty"`
	Photo *string `json:"photo,omitempty"`
	Pmiddlename *string `json:"pmiddlename,omitempty"`
	Psurname *string `json:"psurname,omitempty"`
	Nspokenlang *string `json:"nspokenlang,omitempty"`
	Ospokenlang *string `json:"ospokenlang,omitempty"`
	Religion *string `json:"religion,omitempty"`
	ResidenceTown *string `json:"residence_Town,omitempty"`
	ResidenceLga *string `json:"residence_lga,omitempty"`
	ResidenceState *string `json:"residence_state,omitempty"`
	Residencestatus *string `json:"residencestatus,omitempty"`
	ResidenceAddressLine1 *string `json:"residence_AddressLine1,omitempty"`
	ResidenceAddressLine2 *string `json:"residence_AddressLine2,omitempty"`
	SelfOriginLga *string `json:"self_origin_lga,omitempty"`
	SelfOriginPlace *string `json:"self_origin_place,omitempty"`
	SelfOriginState *string `json:"self_origin_state,omitempty"`
	Signature *string `json:"signature,omitempty"`
	Nationality *string `json:"nationality,omitempty"`
	Gender *string `json:"gender,omitempty"`
	TrackingId *string `json:"trackingId,omitempty"`
	SelfieVerification *VerifySelfieNinResponseEntitySelfieVerification `json:"selfie_verification,omitempty"`
}

// NewVerifySelfieNinResponseEntity instantiates a new VerifySelfieNinResponseEntity object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVerifySelfieNinResponseEntity() *VerifySelfieNinResponseEntity {
	this := VerifySelfieNinResponseEntity{}
	return &this
}

// NewVerifySelfieNinResponseEntityWithDefaults instantiates a new VerifySelfieNinResponseEntity object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVerifySelfieNinResponseEntityWithDefaults() *VerifySelfieNinResponseEntity {
	this := VerifySelfieNinResponseEntity{}
	return &this
}

// GetTitle returns the Title field value if set, zero value otherwise.
func (o *VerifySelfieNinResponseEntity) GetTitle() string {
	if o == nil || isNil(o.Title) {
		var ret string
		return ret
	}
	return *o.Title
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VerifySelfieNinResponseEntity) GetTitleOk() (*string, bool) {
	if o == nil || isNil(o.Title) {
    return nil, false
	}
	return o.Title, true
}

// HasTitle returns a boolean if a field has been set.
func (o *VerifySelfieNinResponseEntity) HasTitle() bool {
	if o != nil && !isNil(o.Title) {
		return true
	}

	return false
}

// SetTitle gets a reference to the given string and assigns it to the Title field.
func (o *VerifySelfieNinResponseEntity) SetTitle(v string) {
	o.Title = &v
}

// GetNin returns the Nin field value if set, zero value otherwise.
func (o *VerifySelfieNinResponseEntity) GetNin() string {
	if o == nil || isNil(o.Nin) {
		var ret string
		return ret
	}
	return *o.Nin
}

// GetNinOk returns a tuple with the Nin field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VerifySelfieNinResponseEntity) GetNinOk() (*string, bool) {
	if o == nil || isNil(o.Nin) {
    return nil, false
	}
	return o.Nin, true
}

// HasNin returns a boolean if a field has been set.
func (o *VerifySelfieNinResponseEntity) HasNin() bool {
	if o != nil && !isNil(o.Nin) {
		return true
	}

	return false
}

// SetNin gets a reference to the given string and assigns it to the Nin field.
func (o *VerifySelfieNinResponseEntity) SetNin(v string) {
	o.Nin = &v
}

// GetFirstname returns the Firstname field value if set, zero value otherwise.
func (o *VerifySelfieNinResponseEntity) GetFirstname() string {
	if o == nil || isNil(o.Firstname) {
		var ret string
		return ret
	}
	return *o.Firstname
}

// GetFirstnameOk returns a tuple with the Firstname field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VerifySelfieNinResponseEntity) GetFirstnameOk() (*string, bool) {
	if o == nil || isNil(o.Firstname) {
    return nil, false
	}
	return o.Firstname, true
}

// HasFirstname returns a boolean if a field has been set.
func (o *VerifySelfieNinResponseEntity) HasFirstname() bool {
	if o != nil && !isNil(o.Firstname) {
		return true
	}

	return false
}

// SetFirstname gets a reference to the given string and assigns it to the Firstname field.
func (o *VerifySelfieNinResponseEntity) SetFirstname(v string) {
	o.Firstname = &v
}

// GetMiddlename returns the Middlename field value if set, zero value otherwise.
func (o *VerifySelfieNinResponseEntity) GetMiddlename() string {
	if o == nil || isNil(o.Middlename) {
		var ret string
		return ret
	}
	return *o.Middlename
}

// GetMiddlenameOk returns a tuple with the Middlename field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VerifySelfieNinResponseEntity) GetMiddlenameOk() (*string, bool) {
	if o == nil || isNil(o.Middlename) {
    return nil, false
	}
	return o.Middlename, true
}

// HasMiddlename returns a boolean if a field has been set.
func (o *VerifySelfieNinResponseEntity) HasMiddlename() bool {
	if o != nil && !isNil(o.Middlename) {
		return true
	}

	return false
}

// SetMiddlename gets a reference to the given string and assigns it to the Middlename field.
func (o *VerifySelfieNinResponseEntity) SetMiddlename(v string) {
	o.Middlename = &v
}

// GetSurname returns the Surname field value if set, zero value otherwise.
func (o *VerifySelfieNinResponseEntity) GetSurname() string {
	if o == nil || isNil(o.Surname) {
		var ret string
		return ret
	}
	return *o.Surname
}

// GetSurnameOk returns a tuple with the Surname field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VerifySelfieNinResponseEntity) GetSurnameOk() (*string, bool) {
	if o == nil || isNil(o.Surname) {
    return nil, false
	}
	return o.Surname, true
}

// HasSurname returns a boolean if a field has been set.
func (o *VerifySelfieNinResponseEntity) HasSurname() bool {
	if o != nil && !isNil(o.Surname) {
		return true
	}

	return false
}

// SetSurname gets a reference to the given string and assigns it to the Surname field.
func (o *VerifySelfieNinResponseEntity) SetSurname(v string) {
	o.Surname = &v
}

// GetMaidenname returns the Maidenname field value if set, zero value otherwise.
func (o *VerifySelfieNinResponseEntity) GetMaidenname() string {
	if o == nil || isNil(o.Maidenname) {
		var ret string
		return ret
	}
	return *o.Maidenname
}

// GetMaidennameOk returns a tuple with the Maidenname field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VerifySelfieNinResponseEntity) GetMaidennameOk() (*string, bool) {
	if o == nil || isNil(o.Maidenname) {
    return nil, false
	}
	return o.Maidenname, true
}

// HasMaidenname returns a boolean if a field has been set.
func (o *VerifySelfieNinResponseEntity) HasMaidenname() bool {
	if o != nil && !isNil(o.Maidenname) {
		return true
	}

	return false
}

// SetMaidenname gets a reference to the given string and assigns it to the Maidenname field.
func (o *VerifySelfieNinResponseEntity) SetMaidenname(v string) {
	o.Maidenname = &v
}

// GetTelephoneno returns the Telephoneno field value if set, zero value otherwise.
func (o *VerifySelfieNinResponseEntity) GetTelephoneno() string {
	if o == nil || isNil(o.Telephoneno) {
		var ret string
		return ret
	}
	return *o.Telephoneno
}

// GetTelephonenoOk returns a tuple with the Telephoneno field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VerifySelfieNinResponseEntity) GetTelephonenoOk() (*string, bool) {
	if o == nil || isNil(o.Telephoneno) {
    return nil, false
	}
	return o.Telephoneno, true
}

// HasTelephoneno returns a boolean if a field has been set.
func (o *VerifySelfieNinResponseEntity) HasTelephoneno() bool {
	if o != nil && !isNil(o.Telephoneno) {
		return true
	}

	return false
}

// SetTelephoneno gets a reference to the given string and assigns it to the Telephoneno field.
func (o *VerifySelfieNinResponseEntity) SetTelephoneno(v string) {
	o.Telephoneno = &v
}

// GetState returns the State field value if set, zero value otherwise.
func (o *VerifySelfieNinResponseEntity) GetState() string {
	if o == nil || isNil(o.State) {
		var ret string
		return ret
	}
	return *o.State
}

// GetStateOk returns a tuple with the State field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VerifySelfieNinResponseEntity) GetStateOk() (*string, bool) {
	if o == nil || isNil(o.State) {
    return nil, false
	}
	return o.State, true
}

// HasState returns a boolean if a field has been set.
func (o *VerifySelfieNinResponseEntity) HasState() bool {
	if o != nil && !isNil(o.State) {
		return true
	}

	return false
}

// SetState gets a reference to the given string and assigns it to the State field.
func (o *VerifySelfieNinResponseEntity) SetState(v string) {
	o.State = &v
}

// GetPlace returns the Place field value if set, zero value otherwise.
func (o *VerifySelfieNinResponseEntity) GetPlace() string {
	if o == nil || isNil(o.Place) {
		var ret string
		return ret
	}
	return *o.Place
}

// GetPlaceOk returns a tuple with the Place field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VerifySelfieNinResponseEntity) GetPlaceOk() (*string, bool) {
	if o == nil || isNil(o.Place) {
    return nil, false
	}
	return o.Place, true
}

// HasPlace returns a boolean if a field has been set.
func (o *VerifySelfieNinResponseEntity) HasPlace() bool {
	if o != nil && !isNil(o.Place) {
		return true
	}

	return false
}

// SetPlace gets a reference to the given string and assigns it to the Place field.
func (o *VerifySelfieNinResponseEntity) SetPlace(v string) {
	o.Place = &v
}

// GetProfession returns the Profession field value if set, zero value otherwise.
func (o *VerifySelfieNinResponseEntity) GetProfession() string {
	if o == nil || isNil(o.Profession) {
		var ret string
		return ret
	}
	return *o.Profession
}

// GetProfessionOk returns a tuple with the Profession field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VerifySelfieNinResponseEntity) GetProfessionOk() (*string, bool) {
	if o == nil || isNil(o.Profession) {
    return nil, false
	}
	return o.Profession, true
}

// HasProfession returns a boolean if a field has been set.
func (o *VerifySelfieNinResponseEntity) HasProfession() bool {
	if o != nil && !isNil(o.Profession) {
		return true
	}

	return false
}

// SetProfession gets a reference to the given string and assigns it to the Profession field.
func (o *VerifySelfieNinResponseEntity) SetProfession(v string) {
	o.Profession = &v
}

// GetHeight returns the Height field value if set, zero value otherwise.
func (o *VerifySelfieNinResponseEntity) GetHeight() string {
	if o == nil || isNil(o.Height) {
		var ret string
		return ret
	}
	return *o.Height
}

// GetHeightOk returns a tuple with the Height field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VerifySelfieNinResponseEntity) GetHeightOk() (*string, bool) {
	if o == nil || isNil(o.Height) {
    return nil, false
	}
	return o.Height, true
}

// HasHeight returns a boolean if a field has been set.
func (o *VerifySelfieNinResponseEntity) HasHeight() bool {
	if o != nil && !isNil(o.Height) {
		return true
	}

	return false
}

// SetHeight gets a reference to the given string and assigns it to the Height field.
func (o *VerifySelfieNinResponseEntity) SetHeight(v string) {
	o.Height = &v
}

// GetEmail returns the Email field value if set, zero value otherwise.
func (o *VerifySelfieNinResponseEntity) GetEmail() string {
	if o == nil || isNil(o.Email) {
		var ret string
		return ret
	}
	return *o.Email
}

// GetEmailOk returns a tuple with the Email field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VerifySelfieNinResponseEntity) GetEmailOk() (*string, bool) {
	if o == nil || isNil(o.Email) {
    return nil, false
	}
	return o.Email, true
}

// HasEmail returns a boolean if a field has been set.
func (o *VerifySelfieNinResponseEntity) HasEmail() bool {
	if o != nil && !isNil(o.Email) {
		return true
	}

	return false
}

// SetEmail gets a reference to the given string and assigns it to the Email field.
func (o *VerifySelfieNinResponseEntity) SetEmail(v string) {
	o.Email = &v
}

// GetBirthdate returns the Birthdate field value if set, zero value otherwise.
func (o *VerifySelfieNinResponseEntity) GetBirthdate() string {
	if o == nil || isNil(o.Birthdate) {
		var ret string
		return ret
	}
	return *o.Birthdate
}

// GetBirthdateOk returns a tuple with the Birthdate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VerifySelfieNinResponseEntity) GetBirthdateOk() (*string, bool) {
	if o == nil || isNil(o.Birthdate) {
    return nil, false
	}
	return o.Birthdate, true
}

// HasBirthdate returns a boolean if a field has been set.
func (o *VerifySelfieNinResponseEntity) HasBirthdate() bool {
	if o != nil && !isNil(o.Birthdate) {
		return true
	}

	return false
}

// SetBirthdate gets a reference to the given string and assigns it to the Birthdate field.
func (o *VerifySelfieNinResponseEntity) SetBirthdate(v string) {
	o.Birthdate = &v
}

// GetBirthstate returns the Birthstate field value if set, zero value otherwise.
func (o *VerifySelfieNinResponseEntity) GetBirthstate() string {
	if o == nil || isNil(o.Birthstate) {
		var ret string
		return ret
	}
	return *o.Birthstate
}

// GetBirthstateOk returns a tuple with the Birthstate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VerifySelfieNinResponseEntity) GetBirthstateOk() (*string, bool) {
	if o == nil || isNil(o.Birthstate) {
    return nil, false
	}
	return o.Birthstate, true
}

// HasBirthstate returns a boolean if a field has been set.
func (o *VerifySelfieNinResponseEntity) HasBirthstate() bool {
	if o != nil && !isNil(o.Birthstate) {
		return true
	}

	return false
}

// SetBirthstate gets a reference to the given string and assigns it to the Birthstate field.
func (o *VerifySelfieNinResponseEntity) SetBirthstate(v string) {
	o.Birthstate = &v
}

// GetBirthcountry returns the Birthcountry field value if set, zero value otherwise.
func (o *VerifySelfieNinResponseEntity) GetBirthcountry() string {
	if o == nil || isNil(o.Birthcountry) {
		var ret string
		return ret
	}
	return *o.Birthcountry
}

// GetBirthcountryOk returns a tuple with the Birthcountry field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VerifySelfieNinResponseEntity) GetBirthcountryOk() (*string, bool) {
	if o == nil || isNil(o.Birthcountry) {
    return nil, false
	}
	return o.Birthcountry, true
}

// HasBirthcountry returns a boolean if a field has been set.
func (o *VerifySelfieNinResponseEntity) HasBirthcountry() bool {
	if o != nil && !isNil(o.Birthcountry) {
		return true
	}

	return false
}

// SetBirthcountry gets a reference to the given string and assigns it to the Birthcountry field.
func (o *VerifySelfieNinResponseEntity) SetBirthcountry(v string) {
	o.Birthcountry = &v
}

// GetCentralID returns the CentralID field value if set, zero value otherwise.
func (o *VerifySelfieNinResponseEntity) GetCentralID() string {
	if o == nil || isNil(o.CentralID) {
		var ret string
		return ret
	}
	return *o.CentralID
}

// GetCentralIDOk returns a tuple with the CentralID field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VerifySelfieNinResponseEntity) GetCentralIDOk() (*string, bool) {
	if o == nil || isNil(o.CentralID) {
    return nil, false
	}
	return o.CentralID, true
}

// HasCentralID returns a boolean if a field has been set.
func (o *VerifySelfieNinResponseEntity) HasCentralID() bool {
	if o != nil && !isNil(o.CentralID) {
		return true
	}

	return false
}

// SetCentralID gets a reference to the given string and assigns it to the CentralID field.
func (o *VerifySelfieNinResponseEntity) SetCentralID(v string) {
	o.CentralID = &v
}

// GetDocumentno returns the Documentno field value if set, zero value otherwise.
func (o *VerifySelfieNinResponseEntity) GetDocumentno() string {
	if o == nil || isNil(o.Documentno) {
		var ret string
		return ret
	}
	return *o.Documentno
}

// GetDocumentnoOk returns a tuple with the Documentno field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VerifySelfieNinResponseEntity) GetDocumentnoOk() (*string, bool) {
	if o == nil || isNil(o.Documentno) {
    return nil, false
	}
	return o.Documentno, true
}

// HasDocumentno returns a boolean if a field has been set.
func (o *VerifySelfieNinResponseEntity) HasDocumentno() bool {
	if o != nil && !isNil(o.Documentno) {
		return true
	}

	return false
}

// SetDocumentno gets a reference to the given string and assigns it to the Documentno field.
func (o *VerifySelfieNinResponseEntity) SetDocumentno(v string) {
	o.Documentno = &v
}

// GetEducationallevel returns the Educationallevel field value if set, zero value otherwise.
func (o *VerifySelfieNinResponseEntity) GetEducationallevel() string {
	if o == nil || isNil(o.Educationallevel) {
		var ret string
		return ret
	}
	return *o.Educationallevel
}

// GetEducationallevelOk returns a tuple with the Educationallevel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VerifySelfieNinResponseEntity) GetEducationallevelOk() (*string, bool) {
	if o == nil || isNil(o.Educationallevel) {
    return nil, false
	}
	return o.Educationallevel, true
}

// HasEducationallevel returns a boolean if a field has been set.
func (o *VerifySelfieNinResponseEntity) HasEducationallevel() bool {
	if o != nil && !isNil(o.Educationallevel) {
		return true
	}

	return false
}

// SetEducationallevel gets a reference to the given string and assigns it to the Educationallevel field.
func (o *VerifySelfieNinResponseEntity) SetEducationallevel(v string) {
	o.Educationallevel = &v
}

// GetEmploymentstatus returns the Employmentstatus field value if set, zero value otherwise.
func (o *VerifySelfieNinResponseEntity) GetEmploymentstatus() string {
	if o == nil || isNil(o.Employmentstatus) {
		var ret string
		return ret
	}
	return *o.Employmentstatus
}

// GetEmploymentstatusOk returns a tuple with the Employmentstatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VerifySelfieNinResponseEntity) GetEmploymentstatusOk() (*string, bool) {
	if o == nil || isNil(o.Employmentstatus) {
    return nil, false
	}
	return o.Employmentstatus, true
}

// HasEmploymentstatus returns a boolean if a field has been set.
func (o *VerifySelfieNinResponseEntity) HasEmploymentstatus() bool {
	if o != nil && !isNil(o.Employmentstatus) {
		return true
	}

	return false
}

// SetEmploymentstatus gets a reference to the given string and assigns it to the Employmentstatus field.
func (o *VerifySelfieNinResponseEntity) SetEmploymentstatus(v string) {
	o.Employmentstatus = &v
}

// GetNokFirstname returns the NokFirstname field value if set, zero value otherwise.
func (o *VerifySelfieNinResponseEntity) GetNokFirstname() string {
	if o == nil || isNil(o.NokFirstname) {
		var ret string
		return ret
	}
	return *o.NokFirstname
}

// GetNokFirstnameOk returns a tuple with the NokFirstname field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VerifySelfieNinResponseEntity) GetNokFirstnameOk() (*string, bool) {
	if o == nil || isNil(o.NokFirstname) {
    return nil, false
	}
	return o.NokFirstname, true
}

// HasNokFirstname returns a boolean if a field has been set.
func (o *VerifySelfieNinResponseEntity) HasNokFirstname() bool {
	if o != nil && !isNil(o.NokFirstname) {
		return true
	}

	return false
}

// SetNokFirstname gets a reference to the given string and assigns it to the NokFirstname field.
func (o *VerifySelfieNinResponseEntity) SetNokFirstname(v string) {
	o.NokFirstname = &v
}

// GetNokLastname returns the NokLastname field value if set, zero value otherwise.
func (o *VerifySelfieNinResponseEntity) GetNokLastname() string {
	if o == nil || isNil(o.NokLastname) {
		var ret string
		return ret
	}
	return *o.NokLastname
}

// GetNokLastnameOk returns a tuple with the NokLastname field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VerifySelfieNinResponseEntity) GetNokLastnameOk() (*string, bool) {
	if o == nil || isNil(o.NokLastname) {
    return nil, false
	}
	return o.NokLastname, true
}

// HasNokLastname returns a boolean if a field has been set.
func (o *VerifySelfieNinResponseEntity) HasNokLastname() bool {
	if o != nil && !isNil(o.NokLastname) {
		return true
	}

	return false
}

// SetNokLastname gets a reference to the given string and assigns it to the NokLastname field.
func (o *VerifySelfieNinResponseEntity) SetNokLastname(v string) {
	o.NokLastname = &v
}

// GetNokMiddlename returns the NokMiddlename field value if set, zero value otherwise.
func (o *VerifySelfieNinResponseEntity) GetNokMiddlename() string {
	if o == nil || isNil(o.NokMiddlename) {
		var ret string
		return ret
	}
	return *o.NokMiddlename
}

// GetNokMiddlenameOk returns a tuple with the NokMiddlename field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VerifySelfieNinResponseEntity) GetNokMiddlenameOk() (*string, bool) {
	if o == nil || isNil(o.NokMiddlename) {
    return nil, false
	}
	return o.NokMiddlename, true
}

// HasNokMiddlename returns a boolean if a field has been set.
func (o *VerifySelfieNinResponseEntity) HasNokMiddlename() bool {
	if o != nil && !isNil(o.NokMiddlename) {
		return true
	}

	return false
}

// SetNokMiddlename gets a reference to the given string and assigns it to the NokMiddlename field.
func (o *VerifySelfieNinResponseEntity) SetNokMiddlename(v string) {
	o.NokMiddlename = &v
}

// GetNokAddress1 returns the NokAddress1 field value if set, zero value otherwise.
func (o *VerifySelfieNinResponseEntity) GetNokAddress1() string {
	if o == nil || isNil(o.NokAddress1) {
		var ret string
		return ret
	}
	return *o.NokAddress1
}

// GetNokAddress1Ok returns a tuple with the NokAddress1 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VerifySelfieNinResponseEntity) GetNokAddress1Ok() (*string, bool) {
	if o == nil || isNil(o.NokAddress1) {
    return nil, false
	}
	return o.NokAddress1, true
}

// HasNokAddress1 returns a boolean if a field has been set.
func (o *VerifySelfieNinResponseEntity) HasNokAddress1() bool {
	if o != nil && !isNil(o.NokAddress1) {
		return true
	}

	return false
}

// SetNokAddress1 gets a reference to the given string and assigns it to the NokAddress1 field.
func (o *VerifySelfieNinResponseEntity) SetNokAddress1(v string) {
	o.NokAddress1 = &v
}

// GetNokAddress2 returns the NokAddress2 field value if set, zero value otherwise.
func (o *VerifySelfieNinResponseEntity) GetNokAddress2() string {
	if o == nil || isNil(o.NokAddress2) {
		var ret string
		return ret
	}
	return *o.NokAddress2
}

// GetNokAddress2Ok returns a tuple with the NokAddress2 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VerifySelfieNinResponseEntity) GetNokAddress2Ok() (*string, bool) {
	if o == nil || isNil(o.NokAddress2) {
    return nil, false
	}
	return o.NokAddress2, true
}

// HasNokAddress2 returns a boolean if a field has been set.
func (o *VerifySelfieNinResponseEntity) HasNokAddress2() bool {
	if o != nil && !isNil(o.NokAddress2) {
		return true
	}

	return false
}

// SetNokAddress2 gets a reference to the given string and assigns it to the NokAddress2 field.
func (o *VerifySelfieNinResponseEntity) SetNokAddress2(v string) {
	o.NokAddress2 = &v
}

// GetNokLga returns the NokLga field value if set, zero value otherwise.
func (o *VerifySelfieNinResponseEntity) GetNokLga() string {
	if o == nil || isNil(o.NokLga) {
		var ret string
		return ret
	}
	return *o.NokLga
}

// GetNokLgaOk returns a tuple with the NokLga field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VerifySelfieNinResponseEntity) GetNokLgaOk() (*string, bool) {
	if o == nil || isNil(o.NokLga) {
    return nil, false
	}
	return o.NokLga, true
}

// HasNokLga returns a boolean if a field has been set.
func (o *VerifySelfieNinResponseEntity) HasNokLga() bool {
	if o != nil && !isNil(o.NokLga) {
		return true
	}

	return false
}

// SetNokLga gets a reference to the given string and assigns it to the NokLga field.
func (o *VerifySelfieNinResponseEntity) SetNokLga(v string) {
	o.NokLga = &v
}

// GetNokState returns the NokState field value if set, zero value otherwise.
func (o *VerifySelfieNinResponseEntity) GetNokState() string {
	if o == nil || isNil(o.NokState) {
		var ret string
		return ret
	}
	return *o.NokState
}

// GetNokStateOk returns a tuple with the NokState field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VerifySelfieNinResponseEntity) GetNokStateOk() (*string, bool) {
	if o == nil || isNil(o.NokState) {
    return nil, false
	}
	return o.NokState, true
}

// HasNokState returns a boolean if a field has been set.
func (o *VerifySelfieNinResponseEntity) HasNokState() bool {
	if o != nil && !isNil(o.NokState) {
		return true
	}

	return false
}

// SetNokState gets a reference to the given string and assigns it to the NokState field.
func (o *VerifySelfieNinResponseEntity) SetNokState(v string) {
	o.NokState = &v
}

// GetNokTown returns the NokTown field value if set, zero value otherwise.
func (o *VerifySelfieNinResponseEntity) GetNokTown() string {
	if o == nil || isNil(o.NokTown) {
		var ret string
		return ret
	}
	return *o.NokTown
}

// GetNokTownOk returns a tuple with the NokTown field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VerifySelfieNinResponseEntity) GetNokTownOk() (*string, bool) {
	if o == nil || isNil(o.NokTown) {
    return nil, false
	}
	return o.NokTown, true
}

// HasNokTown returns a boolean if a field has been set.
func (o *VerifySelfieNinResponseEntity) HasNokTown() bool {
	if o != nil && !isNil(o.NokTown) {
		return true
	}

	return false
}

// SetNokTown gets a reference to the given string and assigns it to the NokTown field.
func (o *VerifySelfieNinResponseEntity) SetNokTown(v string) {
	o.NokTown = &v
}

// GetNokPostalcode returns the NokPostalcode field value if set, zero value otherwise.
func (o *VerifySelfieNinResponseEntity) GetNokPostalcode() string {
	if o == nil || isNil(o.NokPostalcode) {
		var ret string
		return ret
	}
	return *o.NokPostalcode
}

// GetNokPostalcodeOk returns a tuple with the NokPostalcode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VerifySelfieNinResponseEntity) GetNokPostalcodeOk() (*string, bool) {
	if o == nil || isNil(o.NokPostalcode) {
    return nil, false
	}
	return o.NokPostalcode, true
}

// HasNokPostalcode returns a boolean if a field has been set.
func (o *VerifySelfieNinResponseEntity) HasNokPostalcode() bool {
	if o != nil && !isNil(o.NokPostalcode) {
		return true
	}

	return false
}

// SetNokPostalcode gets a reference to the given string and assigns it to the NokPostalcode field.
func (o *VerifySelfieNinResponseEntity) SetNokPostalcode(v string) {
	o.NokPostalcode = &v
}

// GetOthername returns the Othername field value if set, zero value otherwise.
func (o *VerifySelfieNinResponseEntity) GetOthername() string {
	if o == nil || isNil(o.Othername) {
		var ret string
		return ret
	}
	return *o.Othername
}

// GetOthernameOk returns a tuple with the Othername field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VerifySelfieNinResponseEntity) GetOthernameOk() (*string, bool) {
	if o == nil || isNil(o.Othername) {
    return nil, false
	}
	return o.Othername, true
}

// HasOthername returns a boolean if a field has been set.
func (o *VerifySelfieNinResponseEntity) HasOthername() bool {
	if o != nil && !isNil(o.Othername) {
		return true
	}

	return false
}

// SetOthername gets a reference to the given string and assigns it to the Othername field.
func (o *VerifySelfieNinResponseEntity) SetOthername(v string) {
	o.Othername = &v
}

// GetPfirstname returns the Pfirstname field value if set, zero value otherwise.
func (o *VerifySelfieNinResponseEntity) GetPfirstname() string {
	if o == nil || isNil(o.Pfirstname) {
		var ret string
		return ret
	}
	return *o.Pfirstname
}

// GetPfirstnameOk returns a tuple with the Pfirstname field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VerifySelfieNinResponseEntity) GetPfirstnameOk() (*string, bool) {
	if o == nil || isNil(o.Pfirstname) {
    return nil, false
	}
	return o.Pfirstname, true
}

// HasPfirstname returns a boolean if a field has been set.
func (o *VerifySelfieNinResponseEntity) HasPfirstname() bool {
	if o != nil && !isNil(o.Pfirstname) {
		return true
	}

	return false
}

// SetPfirstname gets a reference to the given string and assigns it to the Pfirstname field.
func (o *VerifySelfieNinResponseEntity) SetPfirstname(v string) {
	o.Pfirstname = &v
}

// GetPhoto returns the Photo field value if set, zero value otherwise.
func (o *VerifySelfieNinResponseEntity) GetPhoto() string {
	if o == nil || isNil(o.Photo) {
		var ret string
		return ret
	}
	return *o.Photo
}

// GetPhotoOk returns a tuple with the Photo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VerifySelfieNinResponseEntity) GetPhotoOk() (*string, bool) {
	if o == nil || isNil(o.Photo) {
    return nil, false
	}
	return o.Photo, true
}

// HasPhoto returns a boolean if a field has been set.
func (o *VerifySelfieNinResponseEntity) HasPhoto() bool {
	if o != nil && !isNil(o.Photo) {
		return true
	}

	return false
}

// SetPhoto gets a reference to the given string and assigns it to the Photo field.
func (o *VerifySelfieNinResponseEntity) SetPhoto(v string) {
	o.Photo = &v
}

// GetPmiddlename returns the Pmiddlename field value if set, zero value otherwise.
func (o *VerifySelfieNinResponseEntity) GetPmiddlename() string {
	if o == nil || isNil(o.Pmiddlename) {
		var ret string
		return ret
	}
	return *o.Pmiddlename
}

// GetPmiddlenameOk returns a tuple with the Pmiddlename field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VerifySelfieNinResponseEntity) GetPmiddlenameOk() (*string, bool) {
	if o == nil || isNil(o.Pmiddlename) {
    return nil, false
	}
	return o.Pmiddlename, true
}

// HasPmiddlename returns a boolean if a field has been set.
func (o *VerifySelfieNinResponseEntity) HasPmiddlename() bool {
	if o != nil && !isNil(o.Pmiddlename) {
		return true
	}

	return false
}

// SetPmiddlename gets a reference to the given string and assigns it to the Pmiddlename field.
func (o *VerifySelfieNinResponseEntity) SetPmiddlename(v string) {
	o.Pmiddlename = &v
}

// GetPsurname returns the Psurname field value if set, zero value otherwise.
func (o *VerifySelfieNinResponseEntity) GetPsurname() string {
	if o == nil || isNil(o.Psurname) {
		var ret string
		return ret
	}
	return *o.Psurname
}

// GetPsurnameOk returns a tuple with the Psurname field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VerifySelfieNinResponseEntity) GetPsurnameOk() (*string, bool) {
	if o == nil || isNil(o.Psurname) {
    return nil, false
	}
	return o.Psurname, true
}

// HasPsurname returns a boolean if a field has been set.
func (o *VerifySelfieNinResponseEntity) HasPsurname() bool {
	if o != nil && !isNil(o.Psurname) {
		return true
	}

	return false
}

// SetPsurname gets a reference to the given string and assigns it to the Psurname field.
func (o *VerifySelfieNinResponseEntity) SetPsurname(v string) {
	o.Psurname = &v
}

// GetNspokenlang returns the Nspokenlang field value if set, zero value otherwise.
func (o *VerifySelfieNinResponseEntity) GetNspokenlang() string {
	if o == nil || isNil(o.Nspokenlang) {
		var ret string
		return ret
	}
	return *o.Nspokenlang
}

// GetNspokenlangOk returns a tuple with the Nspokenlang field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VerifySelfieNinResponseEntity) GetNspokenlangOk() (*string, bool) {
	if o == nil || isNil(o.Nspokenlang) {
    return nil, false
	}
	return o.Nspokenlang, true
}

// HasNspokenlang returns a boolean if a field has been set.
func (o *VerifySelfieNinResponseEntity) HasNspokenlang() bool {
	if o != nil && !isNil(o.Nspokenlang) {
		return true
	}

	return false
}

// SetNspokenlang gets a reference to the given string and assigns it to the Nspokenlang field.
func (o *VerifySelfieNinResponseEntity) SetNspokenlang(v string) {
	o.Nspokenlang = &v
}

// GetOspokenlang returns the Ospokenlang field value if set, zero value otherwise.
func (o *VerifySelfieNinResponseEntity) GetOspokenlang() string {
	if o == nil || isNil(o.Ospokenlang) {
		var ret string
		return ret
	}
	return *o.Ospokenlang
}

// GetOspokenlangOk returns a tuple with the Ospokenlang field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VerifySelfieNinResponseEntity) GetOspokenlangOk() (*string, bool) {
	if o == nil || isNil(o.Ospokenlang) {
    return nil, false
	}
	return o.Ospokenlang, true
}

// HasOspokenlang returns a boolean if a field has been set.
func (o *VerifySelfieNinResponseEntity) HasOspokenlang() bool {
	if o != nil && !isNil(o.Ospokenlang) {
		return true
	}

	return false
}

// SetOspokenlang gets a reference to the given string and assigns it to the Ospokenlang field.
func (o *VerifySelfieNinResponseEntity) SetOspokenlang(v string) {
	o.Ospokenlang = &v
}

// GetReligion returns the Religion field value if set, zero value otherwise.
func (o *VerifySelfieNinResponseEntity) GetReligion() string {
	if o == nil || isNil(o.Religion) {
		var ret string
		return ret
	}
	return *o.Religion
}

// GetReligionOk returns a tuple with the Religion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VerifySelfieNinResponseEntity) GetReligionOk() (*string, bool) {
	if o == nil || isNil(o.Religion) {
    return nil, false
	}
	return o.Religion, true
}

// HasReligion returns a boolean if a field has been set.
func (o *VerifySelfieNinResponseEntity) HasReligion() bool {
	if o != nil && !isNil(o.Religion) {
		return true
	}

	return false
}

// SetReligion gets a reference to the given string and assigns it to the Religion field.
func (o *VerifySelfieNinResponseEntity) SetReligion(v string) {
	o.Religion = &v
}

// GetResidenceTown returns the ResidenceTown field value if set, zero value otherwise.
func (o *VerifySelfieNinResponseEntity) GetResidenceTown() string {
	if o == nil || isNil(o.ResidenceTown) {
		var ret string
		return ret
	}
	return *o.ResidenceTown
}

// GetResidenceTownOk returns a tuple with the ResidenceTown field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VerifySelfieNinResponseEntity) GetResidenceTownOk() (*string, bool) {
	if o == nil || isNil(o.ResidenceTown) {
    return nil, false
	}
	return o.ResidenceTown, true
}

// HasResidenceTown returns a boolean if a field has been set.
func (o *VerifySelfieNinResponseEntity) HasResidenceTown() bool {
	if o != nil && !isNil(o.ResidenceTown) {
		return true
	}

	return false
}

// SetResidenceTown gets a reference to the given string and assigns it to the ResidenceTown field.
func (o *VerifySelfieNinResponseEntity) SetResidenceTown(v string) {
	o.ResidenceTown = &v
}

// GetResidenceLga returns the ResidenceLga field value if set, zero value otherwise.
func (o *VerifySelfieNinResponseEntity) GetResidenceLga() string {
	if o == nil || isNil(o.ResidenceLga) {
		var ret string
		return ret
	}
	return *o.ResidenceLga
}

// GetResidenceLgaOk returns a tuple with the ResidenceLga field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VerifySelfieNinResponseEntity) GetResidenceLgaOk() (*string, bool) {
	if o == nil || isNil(o.ResidenceLga) {
    return nil, false
	}
	return o.ResidenceLga, true
}

// HasResidenceLga returns a boolean if a field has been set.
func (o *VerifySelfieNinResponseEntity) HasResidenceLga() bool {
	if o != nil && !isNil(o.ResidenceLga) {
		return true
	}

	return false
}

// SetResidenceLga gets a reference to the given string and assigns it to the ResidenceLga field.
func (o *VerifySelfieNinResponseEntity) SetResidenceLga(v string) {
	o.ResidenceLga = &v
}

// GetResidenceState returns the ResidenceState field value if set, zero value otherwise.
func (o *VerifySelfieNinResponseEntity) GetResidenceState() string {
	if o == nil || isNil(o.ResidenceState) {
		var ret string
		return ret
	}
	return *o.ResidenceState
}

// GetResidenceStateOk returns a tuple with the ResidenceState field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VerifySelfieNinResponseEntity) GetResidenceStateOk() (*string, bool) {
	if o == nil || isNil(o.ResidenceState) {
    return nil, false
	}
	return o.ResidenceState, true
}

// HasResidenceState returns a boolean if a field has been set.
func (o *VerifySelfieNinResponseEntity) HasResidenceState() bool {
	if o != nil && !isNil(o.ResidenceState) {
		return true
	}

	return false
}

// SetResidenceState gets a reference to the given string and assigns it to the ResidenceState field.
func (o *VerifySelfieNinResponseEntity) SetResidenceState(v string) {
	o.ResidenceState = &v
}

// GetResidencestatus returns the Residencestatus field value if set, zero value otherwise.
func (o *VerifySelfieNinResponseEntity) GetResidencestatus() string {
	if o == nil || isNil(o.Residencestatus) {
		var ret string
		return ret
	}
	return *o.Residencestatus
}

// GetResidencestatusOk returns a tuple with the Residencestatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VerifySelfieNinResponseEntity) GetResidencestatusOk() (*string, bool) {
	if o == nil || isNil(o.Residencestatus) {
    return nil, false
	}
	return o.Residencestatus, true
}

// HasResidencestatus returns a boolean if a field has been set.
func (o *VerifySelfieNinResponseEntity) HasResidencestatus() bool {
	if o != nil && !isNil(o.Residencestatus) {
		return true
	}

	return false
}

// SetResidencestatus gets a reference to the given string and assigns it to the Residencestatus field.
func (o *VerifySelfieNinResponseEntity) SetResidencestatus(v string) {
	o.Residencestatus = &v
}

// GetResidenceAddressLine1 returns the ResidenceAddressLine1 field value if set, zero value otherwise.
func (o *VerifySelfieNinResponseEntity) GetResidenceAddressLine1() string {
	if o == nil || isNil(o.ResidenceAddressLine1) {
		var ret string
		return ret
	}
	return *o.ResidenceAddressLine1
}

// GetResidenceAddressLine1Ok returns a tuple with the ResidenceAddressLine1 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VerifySelfieNinResponseEntity) GetResidenceAddressLine1Ok() (*string, bool) {
	if o == nil || isNil(o.ResidenceAddressLine1) {
    return nil, false
	}
	return o.ResidenceAddressLine1, true
}

// HasResidenceAddressLine1 returns a boolean if a field has been set.
func (o *VerifySelfieNinResponseEntity) HasResidenceAddressLine1() bool {
	if o != nil && !isNil(o.ResidenceAddressLine1) {
		return true
	}

	return false
}

// SetResidenceAddressLine1 gets a reference to the given string and assigns it to the ResidenceAddressLine1 field.
func (o *VerifySelfieNinResponseEntity) SetResidenceAddressLine1(v string) {
	o.ResidenceAddressLine1 = &v
}

// GetResidenceAddressLine2 returns the ResidenceAddressLine2 field value if set, zero value otherwise.
func (o *VerifySelfieNinResponseEntity) GetResidenceAddressLine2() string {
	if o == nil || isNil(o.ResidenceAddressLine2) {
		var ret string
		return ret
	}
	return *o.ResidenceAddressLine2
}

// GetResidenceAddressLine2Ok returns a tuple with the ResidenceAddressLine2 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VerifySelfieNinResponseEntity) GetResidenceAddressLine2Ok() (*string, bool) {
	if o == nil || isNil(o.ResidenceAddressLine2) {
    return nil, false
	}
	return o.ResidenceAddressLine2, true
}

// HasResidenceAddressLine2 returns a boolean if a field has been set.
func (o *VerifySelfieNinResponseEntity) HasResidenceAddressLine2() bool {
	if o != nil && !isNil(o.ResidenceAddressLine2) {
		return true
	}

	return false
}

// SetResidenceAddressLine2 gets a reference to the given string and assigns it to the ResidenceAddressLine2 field.
func (o *VerifySelfieNinResponseEntity) SetResidenceAddressLine2(v string) {
	o.ResidenceAddressLine2 = &v
}

// GetSelfOriginLga returns the SelfOriginLga field value if set, zero value otherwise.
func (o *VerifySelfieNinResponseEntity) GetSelfOriginLga() string {
	if o == nil || isNil(o.SelfOriginLga) {
		var ret string
		return ret
	}
	return *o.SelfOriginLga
}

// GetSelfOriginLgaOk returns a tuple with the SelfOriginLga field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VerifySelfieNinResponseEntity) GetSelfOriginLgaOk() (*string, bool) {
	if o == nil || isNil(o.SelfOriginLga) {
    return nil, false
	}
	return o.SelfOriginLga, true
}

// HasSelfOriginLga returns a boolean if a field has been set.
func (o *VerifySelfieNinResponseEntity) HasSelfOriginLga() bool {
	if o != nil && !isNil(o.SelfOriginLga) {
		return true
	}

	return false
}

// SetSelfOriginLga gets a reference to the given string and assigns it to the SelfOriginLga field.
func (o *VerifySelfieNinResponseEntity) SetSelfOriginLga(v string) {
	o.SelfOriginLga = &v
}

// GetSelfOriginPlace returns the SelfOriginPlace field value if set, zero value otherwise.
func (o *VerifySelfieNinResponseEntity) GetSelfOriginPlace() string {
	if o == nil || isNil(o.SelfOriginPlace) {
		var ret string
		return ret
	}
	return *o.SelfOriginPlace
}

// GetSelfOriginPlaceOk returns a tuple with the SelfOriginPlace field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VerifySelfieNinResponseEntity) GetSelfOriginPlaceOk() (*string, bool) {
	if o == nil || isNil(o.SelfOriginPlace) {
    return nil, false
	}
	return o.SelfOriginPlace, true
}

// HasSelfOriginPlace returns a boolean if a field has been set.
func (o *VerifySelfieNinResponseEntity) HasSelfOriginPlace() bool {
	if o != nil && !isNil(o.SelfOriginPlace) {
		return true
	}

	return false
}

// SetSelfOriginPlace gets a reference to the given string and assigns it to the SelfOriginPlace field.
func (o *VerifySelfieNinResponseEntity) SetSelfOriginPlace(v string) {
	o.SelfOriginPlace = &v
}

// GetSelfOriginState returns the SelfOriginState field value if set, zero value otherwise.
func (o *VerifySelfieNinResponseEntity) GetSelfOriginState() string {
	if o == nil || isNil(o.SelfOriginState) {
		var ret string
		return ret
	}
	return *o.SelfOriginState
}

// GetSelfOriginStateOk returns a tuple with the SelfOriginState field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VerifySelfieNinResponseEntity) GetSelfOriginStateOk() (*string, bool) {
	if o == nil || isNil(o.SelfOriginState) {
    return nil, false
	}
	return o.SelfOriginState, true
}

// HasSelfOriginState returns a boolean if a field has been set.
func (o *VerifySelfieNinResponseEntity) HasSelfOriginState() bool {
	if o != nil && !isNil(o.SelfOriginState) {
		return true
	}

	return false
}

// SetSelfOriginState gets a reference to the given string and assigns it to the SelfOriginState field.
func (o *VerifySelfieNinResponseEntity) SetSelfOriginState(v string) {
	o.SelfOriginState = &v
}

// GetSignature returns the Signature field value if set, zero value otherwise.
func (o *VerifySelfieNinResponseEntity) GetSignature() string {
	if o == nil || isNil(o.Signature) {
		var ret string
		return ret
	}
	return *o.Signature
}

// GetSignatureOk returns a tuple with the Signature field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VerifySelfieNinResponseEntity) GetSignatureOk() (*string, bool) {
	if o == nil || isNil(o.Signature) {
    return nil, false
	}
	return o.Signature, true
}

// HasSignature returns a boolean if a field has been set.
func (o *VerifySelfieNinResponseEntity) HasSignature() bool {
	if o != nil && !isNil(o.Signature) {
		return true
	}

	return false
}

// SetSignature gets a reference to the given string and assigns it to the Signature field.
func (o *VerifySelfieNinResponseEntity) SetSignature(v string) {
	o.Signature = &v
}

// GetNationality returns the Nationality field value if set, zero value otherwise.
func (o *VerifySelfieNinResponseEntity) GetNationality() string {
	if o == nil || isNil(o.Nationality) {
		var ret string
		return ret
	}
	return *o.Nationality
}

// GetNationalityOk returns a tuple with the Nationality field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VerifySelfieNinResponseEntity) GetNationalityOk() (*string, bool) {
	if o == nil || isNil(o.Nationality) {
    return nil, false
	}
	return o.Nationality, true
}

// HasNationality returns a boolean if a field has been set.
func (o *VerifySelfieNinResponseEntity) HasNationality() bool {
	if o != nil && !isNil(o.Nationality) {
		return true
	}

	return false
}

// SetNationality gets a reference to the given string and assigns it to the Nationality field.
func (o *VerifySelfieNinResponseEntity) SetNationality(v string) {
	o.Nationality = &v
}

// GetGender returns the Gender field value if set, zero value otherwise.
func (o *VerifySelfieNinResponseEntity) GetGender() string {
	if o == nil || isNil(o.Gender) {
		var ret string
		return ret
	}
	return *o.Gender
}

// GetGenderOk returns a tuple with the Gender field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VerifySelfieNinResponseEntity) GetGenderOk() (*string, bool) {
	if o == nil || isNil(o.Gender) {
    return nil, false
	}
	return o.Gender, true
}

// HasGender returns a boolean if a field has been set.
func (o *VerifySelfieNinResponseEntity) HasGender() bool {
	if o != nil && !isNil(o.Gender) {
		return true
	}

	return false
}

// SetGender gets a reference to the given string and assigns it to the Gender field.
func (o *VerifySelfieNinResponseEntity) SetGender(v string) {
	o.Gender = &v
}

// GetTrackingId returns the TrackingId field value if set, zero value otherwise.
func (o *VerifySelfieNinResponseEntity) GetTrackingId() string {
	if o == nil || isNil(o.TrackingId) {
		var ret string
		return ret
	}
	return *o.TrackingId
}

// GetTrackingIdOk returns a tuple with the TrackingId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VerifySelfieNinResponseEntity) GetTrackingIdOk() (*string, bool) {
	if o == nil || isNil(o.TrackingId) {
    return nil, false
	}
	return o.TrackingId, true
}

// HasTrackingId returns a boolean if a field has been set.
func (o *VerifySelfieNinResponseEntity) HasTrackingId() bool {
	if o != nil && !isNil(o.TrackingId) {
		return true
	}

	return false
}

// SetTrackingId gets a reference to the given string and assigns it to the TrackingId field.
func (o *VerifySelfieNinResponseEntity) SetTrackingId(v string) {
	o.TrackingId = &v
}

// GetSelfieVerification returns the SelfieVerification field value if set, zero value otherwise.
func (o *VerifySelfieNinResponseEntity) GetSelfieVerification() VerifySelfieNinResponseEntitySelfieVerification {
	if o == nil || isNil(o.SelfieVerification) {
		var ret VerifySelfieNinResponseEntitySelfieVerification
		return ret
	}
	return *o.SelfieVerification
}

// GetSelfieVerificationOk returns a tuple with the SelfieVerification field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VerifySelfieNinResponseEntity) GetSelfieVerificationOk() (*VerifySelfieNinResponseEntitySelfieVerification, bool) {
	if o == nil || isNil(o.SelfieVerification) {
    return nil, false
	}
	return o.SelfieVerification, true
}

// HasSelfieVerification returns a boolean if a field has been set.
func (o *VerifySelfieNinResponseEntity) HasSelfieVerification() bool {
	if o != nil && !isNil(o.SelfieVerification) {
		return true
	}

	return false
}

// SetSelfieVerification gets a reference to the given VerifySelfieNinResponseEntitySelfieVerification and assigns it to the SelfieVerification field.
func (o *VerifySelfieNinResponseEntity) SetSelfieVerification(v VerifySelfieNinResponseEntitySelfieVerification) {
	o.SelfieVerification = &v
}

func (o VerifySelfieNinResponseEntity) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Title) {
		toSerialize["title"] = o.Title
	}
	if !isNil(o.Nin) {
		toSerialize["nin"] = o.Nin
	}
	if !isNil(o.Firstname) {
		toSerialize["firstname"] = o.Firstname
	}
	if !isNil(o.Middlename) {
		toSerialize["middlename"] = o.Middlename
	}
	if !isNil(o.Surname) {
		toSerialize["surname"] = o.Surname
	}
	if !isNil(o.Maidenname) {
		toSerialize["maidenname"] = o.Maidenname
	}
	if !isNil(o.Telephoneno) {
		toSerialize["telephoneno"] = o.Telephoneno
	}
	if !isNil(o.State) {
		toSerialize["state"] = o.State
	}
	if !isNil(o.Place) {
		toSerialize["place"] = o.Place
	}
	if !isNil(o.Profession) {
		toSerialize["profession"] = o.Profession
	}
	if !isNil(o.Height) {
		toSerialize["height"] = o.Height
	}
	if !isNil(o.Email) {
		toSerialize["email"] = o.Email
	}
	if !isNil(o.Birthdate) {
		toSerialize["birthdate"] = o.Birthdate
	}
	if !isNil(o.Birthstate) {
		toSerialize["birthstate"] = o.Birthstate
	}
	if !isNil(o.Birthcountry) {
		toSerialize["birthcountry"] = o.Birthcountry
	}
	if !isNil(o.CentralID) {
		toSerialize["centralID"] = o.CentralID
	}
	if !isNil(o.Documentno) {
		toSerialize["documentno"] = o.Documentno
	}
	if !isNil(o.Educationallevel) {
		toSerialize["educationallevel"] = o.Educationallevel
	}
	if !isNil(o.Employmentstatus) {
		toSerialize["employmentstatus"] = o.Employmentstatus
	}
	if !isNil(o.NokFirstname) {
		toSerialize["nok_firstname"] = o.NokFirstname
	}
	if !isNil(o.NokLastname) {
		toSerialize["nok_lastname"] = o.NokLastname
	}
	if !isNil(o.NokMiddlename) {
		toSerialize["nok_middlename"] = o.NokMiddlename
	}
	if !isNil(o.NokAddress1) {
		toSerialize["nok_address1"] = o.NokAddress1
	}
	if !isNil(o.NokAddress2) {
		toSerialize["nok_address2"] = o.NokAddress2
	}
	if !isNil(o.NokLga) {
		toSerialize["nok_lga"] = o.NokLga
	}
	if !isNil(o.NokState) {
		toSerialize["nok_state"] = o.NokState
	}
	if !isNil(o.NokTown) {
		toSerialize["nok_town"] = o.NokTown
	}
	if !isNil(o.NokPostalcode) {
		toSerialize["nok_postalcode"] = o.NokPostalcode
	}
	if !isNil(o.Othername) {
		toSerialize["othername"] = o.Othername
	}
	if !isNil(o.Pfirstname) {
		toSerialize["pfirstname"] = o.Pfirstname
	}
	if !isNil(o.Photo) {
		toSerialize["photo"] = o.Photo
	}
	if !isNil(o.Pmiddlename) {
		toSerialize["pmiddlename"] = o.Pmiddlename
	}
	if !isNil(o.Psurname) {
		toSerialize["psurname"] = o.Psurname
	}
	if !isNil(o.Nspokenlang) {
		toSerialize["nspokenlang"] = o.Nspokenlang
	}
	if !isNil(o.Ospokenlang) {
		toSerialize["ospokenlang"] = o.Ospokenlang
	}
	if !isNil(o.Religion) {
		toSerialize["religion"] = o.Religion
	}
	if !isNil(o.ResidenceTown) {
		toSerialize["residence_Town"] = o.ResidenceTown
	}
	if !isNil(o.ResidenceLga) {
		toSerialize["residence_lga"] = o.ResidenceLga
	}
	if !isNil(o.ResidenceState) {
		toSerialize["residence_state"] = o.ResidenceState
	}
	if !isNil(o.Residencestatus) {
		toSerialize["residencestatus"] = o.Residencestatus
	}
	if !isNil(o.ResidenceAddressLine1) {
		toSerialize["residence_AddressLine1"] = o.ResidenceAddressLine1
	}
	if !isNil(o.ResidenceAddressLine2) {
		toSerialize["residence_AddressLine2"] = o.ResidenceAddressLine2
	}
	if !isNil(o.SelfOriginLga) {
		toSerialize["self_origin_lga"] = o.SelfOriginLga
	}
	if !isNil(o.SelfOriginPlace) {
		toSerialize["self_origin_place"] = o.SelfOriginPlace
	}
	if !isNil(o.SelfOriginState) {
		toSerialize["self_origin_state"] = o.SelfOriginState
	}
	if !isNil(o.Signature) {
		toSerialize["signature"] = o.Signature
	}
	if !isNil(o.Nationality) {
		toSerialize["nationality"] = o.Nationality
	}
	if !isNil(o.Gender) {
		toSerialize["gender"] = o.Gender
	}
	if !isNil(o.TrackingId) {
		toSerialize["trackingId"] = o.TrackingId
	}
	if !isNil(o.SelfieVerification) {
		toSerialize["selfie_verification"] = o.SelfieVerification
	}
	return json.Marshal(toSerialize)
}

type NullableVerifySelfieNinResponseEntity struct {
	value *VerifySelfieNinResponseEntity
	isSet bool
}

func (v NullableVerifySelfieNinResponseEntity) Get() *VerifySelfieNinResponseEntity {
	return v.value
}

func (v *NullableVerifySelfieNinResponseEntity) Set(val *VerifySelfieNinResponseEntity) {
	v.value = val
	v.isSet = true
}

func (v NullableVerifySelfieNinResponseEntity) IsSet() bool {
	return v.isSet
}

func (v *NullableVerifySelfieNinResponseEntity) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVerifySelfieNinResponseEntity(val *VerifySelfieNinResponseEntity) *NullableVerifySelfieNinResponseEntity {
	return &NullableVerifySelfieNinResponseEntity{value: val, isSet: true}
}

func (v NullableVerifySelfieNinResponseEntity) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVerifySelfieNinResponseEntity) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


